---
title: "Chemistry"
author: "Abby Lewis"
date: "2022-09-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(akima)
library(colorRamps)
source("custom_facets.R")

#Define drawdown lines
lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"), Year = 2022)
```

```{r}
carbon = read_csv("../NutrientData/collation/2022/2022_TOC_collation.csv")
carbon%>%
  filter(Reservoir=="BVR")%>%
  mutate(Date = as.Date(DateTime, format = "%m/%d/%y %H:%M"))%>%
  select(Depth_m, Site, Date, DOC_mgL, DIC_mgL, DC_mgL, DN_mgL)%>%
  group_by(Date, Depth_m)%>%
  filter(40%in%Site)%>%
  pivot_longer(cols = contains("_mg"))%>%
  pivot_wider(names_from = Site, values_from =value, names_prefix = "Site_")%>%
  filter(!is.na(Site_40),
         !is.na(Site_50))%>%
  ggplot(aes(x = Site_50, y = Site_40))+
  geom_point()+
  geom_abline(slope = 1, intercept = 0, alpha = 0.7, lty = 2) +
  facet_wrap_equal(~name, scales = "free")

nuts = read_csv("../NutrientData/collation/2022/2022_soluble_NP_collation.csv")
nuts%>%
  filter(Reservoir=="BVR")%>%
  mutate(Date = as.Date(DateTime, format = "%m/%d/%y %H:%M"))%>%
  select(Depth_m, Site, Date, NH4_ugL, PO4_ugL, NO3NO2_ugL)%>%
  group_by(Date, Depth_m)%>%
  filter(40%in%Site)%>%
  pivot_longer(cols = contains("_ug"))%>%
  pivot_wider(names_from = Site, values_from =value, names_prefix = "Site_")%>%
  filter(!is.na(Site_40),
         !is.na(Site_50))%>%
  ggplot(aes(x = Site_50, y = Site_40))+
  geom_point()+
  geom_abline(slope = 1, intercept = 0, alpha = 0.7, lty = 2) +
  facet_wrap_equal(~name, scales = "free")

chem = nuts%>%
  full_join(carbon)%>%
  filter(Reservoir=="BVR",
         Site == 50)%>%
  mutate(DateTime = as.Date(DateTime, format = "%m/%d/%y %H:%M"))
```


```{r}
#NOTE this is in staging, need to update
inUrl1  <- "https://pasta-s.lternet.edu/package/data/eml/edi/1025/3/509f39850b6f95628d10889d66885b76" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "Rep",     
                    "TN_ugL",     
                    "TP_ugL",     
                    "NH4_ugL",     
                    "NO3NO2_ugL",     
                    "SRP_ugL",     
                    "DOC_mgL",     
                    "DIC_mgL",     
                    "DC_mgL",     
                    "DN_mgL",     
                    "Flag_DateTime",     
                    "Flag_TN_ugL",     
                    "Flag_TP_ugL",     
                    "Flag_NH4_ugL",     
                    "Flag_NO3NO2_ugL",     
                    "Flag_SRP_ugL",     
                    "Flag_DOC_mgL",     
                    "Flag_DIC_mgL",     
                    "Flag_DC_mgL",     
                    "Flag_DN_mgL"    ), check.names=TRUE)
               
unlink(infile1)

dt1 = dt1%>%
  mutate(DateTime=as.Date(DateTime))%>%
  rename(PO4_ugL = SRP_ugL)

chem_full = dt1%>%
  filter(Reservoir=="BVR",
         Site==50,
         year(DateTime)%in% c(2021,2022))

chem_full$Date_22<-chem_full$DateTime
chem_full$Year = year(chem_full$DateTime)
year(chem_full$Date_22)<-2022

chem_full%>%
  filter(Reservoir=="BVR", Site==50)%>%
  ggplot(aes(x = Date_22, y = PO4_ugL, color = as.factor(Depth_m)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  geom_line()+
  geom_point()+
  facet_wrap(~Year)

chem_full%>%
  filter(Reservoir=="BVR", Site==50)%>%
  ggplot(aes(x = Date_22, y = NH4_ugL, color = as.factor(Depth_m)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  geom_line()+
  geom_point()+
  facet_wrap(~Year)

chem_full%>%
  filter(Reservoir=="BVR", Site==50)%>%
  ggplot(aes(x = Date_22, y = NO3NO2_ugL, color = as.factor(Depth_m)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  geom_line()+
  geom_point()+
  facet_wrap(~Year)
```

```{r}
chem_boxplot = chem_full%>%
  filter(Reservoir=="BVR", Site==50,
         month(DateTime)>4,month(DateTime)<10)%>%
  mutate(period = factor(ifelse(Date_22<"2022-05-19","before May 19","after"),levels = c("before May 19","after")),
         Year = as.factor(Year))%>%
  group_by(DateTime)%>%
  filter(Depth_m==0.1|Depth_m == max(Depth_m))%>%
  mutate(Layer = ifelse(Depth_m==0.1,"top (0.1 m)","bottom (lowest depth sampled)"))

library(ggpubr)
p1 = chem_boxplot%>%
  ungroup()%>%
  filter(Layer == "top (0.1 m)")%>%
  select(period, PO4_ugL,NH4_ugL,NO3NO2_ugL,DOC_mgL,Year,Layer)%>%
  pivot_longer(cols = c("PO4_ugL","NH4_ugL","NO3NO2_ugL","DOC_mgL"))%>%
  ggplot(aes(x = period, y = value,color = Year))+
  geom_boxplot(outlier.alpha = 0)+
  geom_point(position = position_jitterdodge())+
  facet_grid(cols = vars(Layer), rows = vars(name), scales= "free")+
  stat_compare_means(label = "p.format",vjust = -1)+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())+
  scale_y_continuous(expand = expansion(mult = c(0.1,.4)))

p2 = chem_boxplot%>%
  ungroup()%>%
  filter(Layer == "bottom (lowest depth sampled)")%>%
  select(period, PO4_ugL,NH4_ugL,NO3NO2_ugL,DOC_mgL,Year,Layer)%>%
  pivot_longer(cols = c("PO4_ugL","NH4_ugL","NO3NO2_ugL","DOC_mgL"))%>%
  ggplot(aes(x = period, y = value,color = Year))+
  geom_boxplot(outlier.alpha = 0)+
  geom_point(position = position_jitterdodge())+
  facet_grid(cols = vars(Layer), rows = vars(name), scales= "free")+
  stat_compare_means(label = "p.format",vjust = -1)+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())+
  scale_y_continuous(expand = expansion(mult = c(0.1,.4)))

ggarrange(p1,p2, common.legend = T, legend = "bottom")
```


Heatmaps
```{r}
cat_long = read.csv("~/Desktop/github/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_BVRplatform/2022/BVR_longoutput_FLARE_2020_2021.csv")

sensor_depth = cat_long%>%
  select(DateTime,Reservoir_depth)%>%
  unique()%>%
  mutate(DateTime = as.POSIXct(DateTime))%>%
  rename(WaterLevel = Reservoir_depth)%>%
  filter(DateTime>=min(chem_full$DateTime, na.rm = T),
         DateTime<=max(chem_full$DateTime, na.rm = T),
         WaterLevel>7.5)%>%
  arrange(DateTime)%>%
  filter(!lag(WaterLevel)-WaterLevel>0.2)%>%
  mutate(Date = as.Date(DateTime))%>%
  group_by(Date)%>%
  summarize(WaterLevel = mean(WaterLevel))%>%
  mutate(Year = year(Date),
         Site = 50)%>%
  group_by(Site)%>%
  mutate(max = max(WaterLevel))%>%
  filter(month(Date)>2,
         month(Date)<10)

chem_bvr = chem_full%>%
  left_join(sensor_depth%>%rename(DateTime=Date))%>%select(-max)%>%
  mutate(height = WaterLevel-Depth_m)%>%
  arrange(height)%>%
  filter(!is.na(height),
         month(DateTime)>2,
         month(DateTime)<10)

chem_bvr%>%
  filter(Year==2021,month(DateTime)==9)

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

vars = c("NH4_ugL","PO4_ugL","DOC_mgL","NO3NO2_ugL")
years = c(2021,2022)

for(var in vars){
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  bvr_comb = chem_bvr%>%
    filter(Depth_m==1000000)
  Sites = c(50)
  for(year in years){
    for(site in Sites){
      bvr<- chem_bvr%>%
        mutate(Year = year(DateTime),
               Date = as.Date(DateTime))%>%
        filter(Site == site,
               !is.na(get(var)),
               !is.na(Depth_m),
               Year==year)%>%
        arrange(NH4_ugL)
      
      bvr_interp <- interp2xyz(interp(bvr$Date,bvr$height,bvr[[var]],xo = seq(min(bvr$Date), max(bvr$Date), .1),yo = seq(min(bvr$height), max(bvr$height), by = .01), duplicate = "mean"),data.frame = T)
      
      interp = interp%>%
        full_join(bvr_interp%>%mutate(Site=site))
      bvr_comb = bvr_comb%>%
        full_join(bvr)%>%
        mutate(max = max(height))
    }
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  #Heatmap
  jpeg(paste0("./Figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot(aes(x=x))+
    geom_raster(aes(fill = z, y = y))+
    scale_y_continuous(expand = c(0,0))+
    labs(x = "", y = "Height above sediments (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(blue2green2red(100))}else{blue2green2red(100)}, na.value="gray", name = var)+
    geom_ribbon(data = sensor_depth, aes(x = Date, ymin= WaterLevel, ymax = max), fill = "white")+
    geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
    scale_x_date(expand = c(0,0))+
    theme_classic()+
    theme(panel.border = element_rect(fill = NA))+
    geom_point(data = bvr_comb, aes(x = Date, y = max), shape = 25, fill = "black", color = "white", size  =2)+
    facet_grid(rows= vars(Site),
               cols = vars(Year),
               scales = "free",
               space = "free"
               )
  print(p)
  dev.off()
}
```

Compare P, DOC, and fluora
```{r}
#Load data
inUrl1  <- "https://pasta.lternet.edu/package/data/eml/edi/272/7/001cb516ad3e8cbabe1fdcf6826a0a45"
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "GreenAlgae_ugL",     
                    "Bluegreens_ugL",     
                    "BrownAlgae_ugL",     
                    "MixedAlgae_ugL",     
                    "YellowSubstances_ugL",     
                    "TotalConc_ugL",     
                    "Transmission",     
                    "Temp_degC",     
                    "RFU_525nm",     
                    "RFU_570nm",     
                    "RFU_610nm",     
                    "RFU_370nm",     
                    "RFU_590nm",     
                    "RFU_470nm",     
                    "Flag_GreenAlgae",     
                    "Flag_BluegreenAlgae",     
                    "Flag_BrownAlgae",     
                    "Flag_MixedAlgae",     
                    "Flag_TotalConc",     
                    "Flag_Temp",     
                    "Flag_Transmission",     
                    "Flag_525nm",     
                    "Flag_570nm",     
                    "Flag_610nm",     
                    "Flag_370nm",     
                    "Flag_590nm",     
                    "Flag_470nm"    ), check.names=TRUE)
               
unlink(infile1)

#Combine current and historical data
fluora = dt1

fluora_surface=fluora%>%
  filter(Reservoir=="BVR",
         Site==50,
         Depth_m<1)%>%
  mutate(DateTime = as.Date(DateTime))%>%
  group_by(DateTime)%>%
  mutate(min_depth = min(Depth_m))%>%
  filter(Depth_m==min_depth)


fluora_surface$DateTime

sum_plot = chem_full%>%
  filter(Depth_m ==0.1)%>%
  select(DateTime, PO4_ugL,DOC_mgL)%>%
  full_join(fluora_surface%>%
              filter(year(DateTime)%in% c(2021,2022)))%>%
  select(DateTime, PO4_ugL,DOC_mgL,Bluegreens_ugL,TotalConc_ugL)%>%
  pivot_longer(cols = c(PO4_ugL,DOC_mgL,Bluegreens_ugL,TotalConc_ugL))%>%
  filter(!is.na(value),
         month(DateTime)>4,
         month(DateTime)<9)%>%
  mutate(Year = year(DateTime))%>%
  mutate(name = factor(name, levels=c("PO4_ugL","TotalConc_ugL","Bluegreens_ugL","DOC_mgL")))

maxes = sum_plot%>%
  group_by(name, Year)%>%
  summarize(max_date = DateTime[which.max(value)])%>%
  filter(Year=="2022")

# New facet label names for sum_plot
fac.labs <- c("SRP (ug/L)","Total phyto. (ug/L)","Cyanobacteria (ug/L)","DOC (mg/L)")
names(fac.labs) <- c("PO4_ugL","TotalConc_ugL","Bluegreens_ugL","DOC_mgL")

jpeg("./Figs/Abby_money_plot_for_WVWA.jpeg", res = 300, width = 6.5, height = 5.6, units = "in")
sum_plot%>%
  ggplot(aes(x = DateTime, y = value, color = name))+
  geom_point()+
  geom_line()+
  geom_vline(aes(xintercept = max_date, color = name), data = maxes, lwd = 2)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_manual(values = c("#202C39","#2DB138","#00BED0","#8E4416"))+
  facet_grid(rows = vars(name), cols = vars(Year), scales = "free", switch = "y",
             labeller = labeller(name = fac.labs))+
  theme_bw()+
  theme(strip.placement = "outside", legend.position = "none",
        strip.text.x = element_text(
        size = 12, face = "bold"
        ),
        axis.title.x = element_blank(),
        strip.background = element_blank(
     ))+
  ylab("")
dev.off()

thermo_depth = read.csv("./Data/thermocline_depth.csv")%>%
  filter(!year(Date)==2020)

light = read.csv("./Data/attenuation_calc.csv")%>%
  filter(year(Date)%in%c(2021,2022))

ctd = read.csv("./Data/CTD at 0.1m.csv")%>%
  filter(year(Date)%in%c(2021,2022))

ghg = read.csv("./Data/GHG at 0.1m.csv")%>%
  filter(year(DateTime)%in%c(2021,2022))

metals = read.csv("./Data/Metals at 0.1m.csv")

cmax_depth = read.csv("./Data/FP_CmaxDepth.csv")
peak_width = read.csv("./Data/FP_PeakWidth.csv")

sum_plot2 = chem_full%>%
  filter(Depth_m ==0.1)%>%
  select(DateTime, PO4_ugL,DOC_mgL,NO3NO2_ugL,NH4_ugL)%>%
  full_join(fluora_surface%>%
              filter(year(DateTime)%in% c(2021,2022)))%>%
  full_join(thermo_depth%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(light%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(ctd%>%mutate(DateTime = as.Date(DateTime))%>%select(-Date))%>%
  full_join(ghg%>%mutate(DateTime = as.Date(DateTime)))%>%
  full_join(metals%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Date_22))%>%
  select(DateTime, PO4_ugL,DOC_mgL,Bluegreens_ugL,TotalConc_ugL,co2_umolL,ch4_umolL,thermo,Zeu,Turbidity_NTU,SpCond_uScm,DO_mgL,NO3NO2_ugL,NH4_ugL, pH,TFe_mgL)%>%
  pivot_longer(cols = c(PO4_ugL,DOC_mgL,Bluegreens_ugL,TotalConc_ugL,co2_umolL,ch4_umolL,thermo,Zeu,Turbidity_NTU,SpCond_uScm,DO_mgL,NO3NO2_ugL,NH4_ugL, pH,TFe_mgL))%>%
  filter(!is.na(value),
         month(DateTime)>4,
         month(DateTime)<9)%>%
  mutate(Year = year(DateTime))%>%
  mutate(name = factor(name, levels=c("PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","co2_umolL","ch4_umolL","Turbidity_NTU","Zeu","thermo","SpCond_uScm","DO_mgL","NO3NO2_ugL","NH4_ugL","TFe_mgL")))

maxes = sum_plot2%>%
  group_by(name, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            min_date = DateTime[which.min(value)])%>%
  filter(Year=="2022")%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL"),min_date,max_date))

# New facet label names for sum_plot
fac.labs <- c("SRP (ug/L)","Total phyto. (ug/L)","Cyanobacteria (ug/L)","pH","DOC (mg/L)","CO2","CH4","Thermocline depth (m)","Euphotic zone (m)","Turbidity (NTU)","SpCond_uScm","DO_mgL","NO3NO2_ugL","NH4_ugL","TFe_mgL")
names(fac.labs) <- c("PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","co2_umolL","ch4_umolL","thermo", "Zeu","Turbidity_NTU","SpCond_uScm","DO_mgL","NO3NO2_ugL","NH4_ugL","TFe_mgL")

jpeg("./Figs/Abby_money_plot_all.jpeg", res = 300, width = 6.5, height = 10, units = "in")
sum_plot2%>%
  mutate(show_points = ifelse(name == "thermo","n","y"))%>%
  ggplot(aes(x = DateTime, y = value, color = name))+
  geom_point(aes(alpha = show_points))+
  scale_alpha_manual(values = c(0,1))+
  geom_line()+
  geom_vline(aes(xintercept = max_date, color = name), data = maxes, lwd = 2)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  facet_grid(rows = vars(name), cols = vars(Year), scales = "free", switch = "y",
             labeller = labeller(name = fac.labs))+
  theme_bw()+
  theme(strip.placement = "outside", legend.position = "none",
        strip.text.x = element_text(
        size = 12, face = "bold"
        ),
        axis.title.x = element_blank(),
        strip.background = element_blank(
     ))+
  ylab("")
dev.off()

sum_plot3 = chem_full%>%
  filter(Depth_m ==0.1)%>%
  select(DateTime, PO4_ugL,DOC_mgL,NO3NO2_ugL,NH4_ugL)%>%
  full_join(fluora_surface%>%
              filter(year(DateTime)%in% c(2021,2022)))%>%
  full_join(thermo_depth%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(light%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(ctd%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Year,-Depth_m))%>%
  full_join(metals%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Date_22))%>%
  select(DateTime, TFe_mgL,TMn_mgL,DOsat_percent,thermo)%>%
  pivot_longer(cols = c(TFe_mgL,TMn_mgL,DOsat_percent,thermo))%>%
  filter(!is.na(value),
         month(DateTime)>4,
         month(DateTime)<9)%>%
  mutate(Year = year(DateTime))%>%
  mutate(name = factor(name, levels=c("thermo","DOsat_percent","TFe_mgL","TMn_mgL")))

maxes = sum_plot3%>%
  group_by(name, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            min_date = DateTime[which.min(value)])%>%
  filter(Year=="2022")%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL","DOsat_percent"),min_date,max_date))

sum_plot3%>%
  group_by(name, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            max = max(value),
            min_date = DateTime[which.min(value)],
            min = min(value))%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL","DOsat_percent"),min_date,max_date))

# New facet label names for sum_plot
fac.labs <- c("Surface DO\n(mgL)","Total Fe\n(mg/L)","Total Mn\n(mg/L)","Thermocline\ndepth (m)","Surface DO\n(% saturation)")
names(fac.labs) <- c("DO_mgL","TFe_mgL","TMn_mgL","thermo","DOsat_percent")
library(ggh4x)
scales <- list(
  scale_y_reverse(limits = c(NA,0)),
  scale_y_continuous(),
  scale_y_continuous(),
  scale_y_continuous()
)
horiz_line = data.frame(name=rep("DOsat_percent",2),y = rep(100,2),Year=c(2021,2022))%>%
  mutate(name = factor(name, levels=c("thermo","DOsat_percent","TFe_mgL","TMn_mgL")))
sum_plot3%>%
  mutate(show_points = ifelse(name == "thermo","n","y"))%>%
  ggplot(aes(x = DateTime, y = value, color = name))+
  geom_hline(aes(yintercept = y),data=horiz_line, color = "cyan4",alpha=0.3,size=1)+
  geom_point(aes(alpha = show_points))+
  geom_line()+
  scale_alpha_manual(values = c(0,1))+
  geom_vline(aes(xintercept = max_date, color = name), data = maxes, lwd = 2, alpha = 0.5)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_manual(values = c("darkblue","cyan4","lightsalmon","coral4"))+
  facet_grid(rows = vars(name), cols = vars(Year), scales = "free", switch = "y",
             labeller = labeller(name = fac.labs))+
  theme_bw()+
  theme(strip.placement = "outside", legend.position = "none",
        strip.text.x = element_text(
        size = 12, face = "bold"
        ),
        axis.title.x = element_blank(),
        strip.background = element_blank(
     ))+
  facetted_pos_scales(y = scales)+
  ylab("")+
  force_panelsizes(rows = unit(.75, "in"),
                   cols = unit(2.5, "in"))
ggsave("./Figs/Abby_money_plot_biogeo.jpeg", dpi = 300, width = 6.5, height = 4)

sum_plot4 = chem_full%>%
  filter(Depth_m ==0.1)%>%
  select(DateTime, TP_ugL, PO4_ugL,DOC_mgL,DIC_mgL,NO3NO2_ugL,NH4_ugL)%>%
  full_join(fluora_surface%>%
              filter(year(DateTime)%in% c(2021,2022)))%>%
  full_join(thermo_depth%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(light%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(ctd%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Reservoir))%>%
  full_join(ghg%>%mutate(DateTime = as.Date(DateTime)))%>%
  select(DateTime, TP_ugL, PO4_ugL,DOC_mgL,TotalConc_ugL,pH,NH4_ugL,co2_umolL,ch4_umolL,Bluegreens_ugL)%>%
  pivot_longer(cols = c(TP_ugL, PO4_ugL,DOC_mgL,TotalConc_ugL,pH,co2_umolL,ch4_umolL,NH4_ugL,Bluegreens_ugL))%>%
  filter(!is.na(value),
         month(DateTime)>4,
         month(DateTime)<9)%>%
  mutate(Year = year(DateTime),
         color = name,
         name = ifelse(name%in%c("TotalConc_ugL","Bluegreens_ugL"),"Phyto",name),
         name = ifelse(name%in%c("TP_ugL","PO4_ugL"),"Phosphorus",name))%>%
  mutate(name = factor(name, levels=c("Phosphorus","Phyto","pH","DOC_mgL","ch4_umolL","co2_umolL","NH4_ugL")),
         color = factor(color, levels=c("TP_ugL","PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","ch4_umolL","co2_umolL","NH4_ugL"),
                        labels=c("TP_ugL","PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","ch4_umolL","co2_umolL","NH4_ugL")))

maxes = sum_plot4%>%
  group_by(name,color, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            min_date = DateTime[which.min(value)])%>%
  filter(Year=="2022")%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL"),min_date,max_date))
maxes%>%
  mutate(max_date=as.Date(max_date, origin="1970-01-01"))
as.Date("2022-07-05")-as.Date("2022-06-27")
as.Date("2022-07-18")-as.Date("2022-06-27")

# New facet label names for sum_plot
fac.labs <- c("Phosphorus\n(ug/L)", "Phyto.\n(ug/L)", "pH", "DOC\n(mg/L)", "CO2\n(µmol/L)", "CH4\n(µmol/L)", "NH4 (µg/L)")
names(fac.labs) <- c("Phosphorus", "Phyto", "pH", "DOC_mgL", "co2_umolL", "ch4_umolL", "NH4_ugL")

my_colors = c("black","grey50","darkgreen","turquoise","blue","#8E4412","skyblue","pink","magenta4")
names(my_colors)=c("TP_ugL","PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","ch4_umolL","co2_umolL","NH4_ugL")

sum_plot4%>%
  ggplot(aes(x = DateTime, y = value, color = color))+
  geom_point()+
  geom_line()+
  geom_vline(aes(xintercept = max_date, color = color), data = maxes, lwd = 2, alpha = 0.5)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_manual(breaks = c("TotalConc_ugL","Bluegreens_ugL"),
                     labels = c("Total (µg/L)","Cyanobacteria (µg/L)"),
                     #limits = c("PO4_ugL","TotalConc_ugL","Bluegreens_ugL","pH","DOC_mgL","ch4_umolL","co2_umolL","NH4_ugL"),
                     values = my_colors
                     )+
  facet_grid(rows = vars(name), cols = vars(Year), scales = "free", switch = "y",
             labeller = labeller(name = fac.labs))+
  theme_bw()+
  theme(strip.placement = "outside", 
        strip.text.x = element_text(
        size = 12, face = "bold"
        ),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        legend.position = c(0.2,0.82),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.key= element_blank(),
        legend.spacing.y = unit(0, 'cm'),
        legend.text=element_text(size=7)
        )+
  guides(color = guide_legend(byrow = TRUE,keyheight = 0.75))+
  ylab("")+
  force_panelsizes(rows = unit(.75, "in"),
                   cols = unit(2.5, "in"))
ggsave("./Figs/Abby_money_plot_doc.jpeg", dpi = 300, width = 6.5, height = 6.5)

sum_plot5 = chem_full%>%
  filter(Depth_m ==0.1)%>%
  select(DateTime, PO4_ugL,DOC_mgL,NO3NO2_ugL,NH4_ugL)%>%
  full_join(fluora_surface%>%
              filter(year(DateTime)%in% c(2021,2022)))%>%
  full_join(thermo_depth%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(light%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(ctd%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Year,-Depth_m))%>%
  full_join(metals%>%mutate(DateTime = as.Date(Date))%>%select(-Date,-Date_22))%>%
  full_join(cmax_depth%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  full_join(peak_width%>%mutate(DateTime = as.Date(Date))%>%select(-Date))%>%
  select(DateTime, Turbidity_NTU, Zeu, CmaxDepth_TotalConc_ugL, CmaxDepth_Bluegreens_ugL, PeakWidth_TotalConc_m, PeakWidth_Bluegreens_m)%>%
  pivot_longer(cols = c(Turbidity_NTU, Zeu, CmaxDepth_TotalConc_ugL, CmaxDepth_Bluegreens_ugL, PeakWidth_TotalConc_m, PeakWidth_Bluegreens_m))%>%
  filter(!is.na(value),
         month(DateTime)>4,
         month(DateTime)<9)%>%
  mutate(Year = year(DateTime),
         color = ifelse(name%in%c("CmaxDepth_TotalConc_ugL", "PeakWidth_TotalConc_m"),"TotalConc_ugL",
                        ifelse(name%in%c("PeakWidth_Bluegreens_m", "CmaxDepth_Bluegreens_ugL"),"Bluegreens_ugL",name)),
         name = ifelse(name%in%c("CmaxDepth_TotalConc_ugL", "CmaxDepth_Bluegreens_ugL"),"Cmax_depth",name),
         name = ifelse(name%in%c("PeakWidth_TotalConc_m", "PeakWidth_Bluegreens_m"),"PeakWidth",name))%>%
  mutate(name = factor(name, levels=c("Turbidity_NTU", "Zeu", "Cmax_depth", "PeakWidth")),
         color = factor(color, levels=c("Turbidity_NTU", "Zeu","TotalConc_ugL", "Bluegreens_ugL")))

maxes = sum_plot5%>%
  group_by(name,color, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            min_date = DateTime[which.min(value)])%>%
  filter(Year=="2022")%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL","Cmax_depth", "PeakWidth"),min_date,max_date))

sum_plot5%>%
  group_by(name,color, Year)%>%
  summarize(max_date = DateTime[which.max(value)],
            max = max(value),
            min_date = DateTime[which.min(value)],
            min = min(value))%>%
  mutate(max_date = ifelse(name %in% c("thermo","Zeu","DO_mgL","Cmax_depth", "PeakWidth"),min_date,max_date),
         max = ifelse(name %in% c("thermo","Zeu","DO_mgL","Cmax_depth", "PeakWidth"),min,max))%>%
  group_by(name,color)%>%
  mutate(pct = (max[Year==2022]-max[Year==2021])/max[Year==2021]*100)

# New facet label names for sum_plot
fac.labs <- c("Turbidity\n(NTU)", "Euphotic zone\ndepth (m)", "C[max]\ndepth(m)", "Peak width\n(m)")
names(fac.labs) <- c("Turbidity_NTU", "Zeu", "Cmax_depth", "PeakWidth")
my_colors = c("grey20","goldenrod","darkgreen","turquoise")
names(my_colors)=c("Turbidity_NTU", "Zeu","TotalConc_ugL", "Bluegreens_ugL")
scales <- list(
  scale_y_continuous(),
  scale_y_reverse(limits = c(NA,0)),
  scale_y_reverse(limits = c(NA,0)),
  scale_y_continuous()
)
sum_plot5%>%
  ggplot(aes(x = DateTime, y = value, color = color))+
  geom_point()+
  geom_line()+
  geom_vline(aes(xintercept = max_date, color = color), data = maxes, lwd = 2, alpha = 0.5)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_manual(breaks = c("TotalConc_ugL","Bluegreens_ugL"),
                     labels = c("Total (µg/L)","Cyanobacteria (µg/L)"),
                     values = my_colors
                     )+
  facet_grid(rows = vars(name), cols = vars(Year), scales = "free", switch = "y",
             labeller = labeller(.rows = fac.labs))+
  theme_bw()+
  theme(strip.placement = "outside", 
        legend.position = c(.2,.42),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.key= element_blank(),
        legend.spacing.y = unit(0, 'cm'),
        legend.text=element_text(size=7),
        strip.text.x = element_text(
          size = 12, face = "bold"
        ),
        axis.title.x = element_blank(),
        strip.background = element_blank(
     ))+
  ylab("")+
  guides(color = guide_legend(byrow = TRUE,keyheight = 0.75))+
  facetted_pos_scales(y = scales)+
  force_panelsizes(rows = unit(.75, "in"),
                   cols = unit(2.5, "in"))

ggsave("./Figs/Abby_money_plot_phytos.jpeg", dpi = 300, width = 6.5, height = 4)
```

