---
title: "Physics"
author: "Abby Lewis"
date: "2022-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rLakeAnalyzer)
library(lubridate)
library(rLakeAnalyzer)
library(akima)
library(colorRamps)
```

```{r}
cat_long = read.csv("~/Desktop/github/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_BVRplatform/2022/BVR_longoutput_FLARE_2020_2021.csv")%>%
  filter(Sensor=="ThermistorTemp")

#Load bathymetry
bathy = read.csv("./Data/Bathymetry_comb.csv")%>%
  filter(Reservoir == "BVR")

cat_depths = cat_long%>%
  mutate(Date = as.Date(as.POSIXct(DateTime)))%>%
  filter(!is.na(Reading))%>%
  group_by(Date)%>%
  dplyr::summarize(WaterLevel = mean(Reservoir_depth))

flexible_bathy = cat_depths%>%
  mutate(Reservoir = "BVR")%>%
  full_join(bathy)%>%
  group_by(Date)%>%
  mutate(Depth_m = Depth_m - (max(Depth_m)-unique(WaterLevel)) + 1)%>%
  filter(Depth_m>=0)

catwalk_format = cat_long%>%
  filter(!is.na(Reading))%>%
  mutate(Date = as.Date(as.POSIXct(DateTime)),
         Sensor_depth = round(Sensor_depth,1)
         )%>%
  group_by(Date)%>%
  mutate(Reservoir_depth = mean(Reservoir_depth))%>%
  group_by(Date, Sensor_depth)%>%
  dplyr::summarize(Reading=mean(Reading,na.rm = T),
                   Reservoir_depth = unique(Reservoir_depth))

schmidts = c()
for(date in unique(catwalk_format$Date)){
  temps = catwalk_format%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  schmidts = c(schmidts, schmidt.stability(wtr = temps$Reading, depths = temps$Sensor_depth, bthA = baths$SA_m2, bthD = baths$Depth_m, sal = rep(0,length(temps$Reading))))
}

schmidt_df = data.frame(Date = unique(catwalk_format$Date), Schmidt = schmidts)%>%
  mutate(Year = year(Date))
schmidt_df$Date_22 = schmidt_df$Date
year(schmidt_df$Date_22)=2022


###
# PLOT RESULTS
###
lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"), Year = 2022)

jpeg("./Figs/Schmidt_exo.jpg",res = 300, units = "in",width = 6, height = 4)
schmidt_fig = schmidt_df%>%
  filter(Year %in% c(2021,2022),
         !is.na(Schmidt))%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Schmidt, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Schmidt stability (J/m^2)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank(),
        legend.position = "none")
schmidt_fig
dev.off()

buoyancy_raw = catwalk_format%>%
  filter(!is.na(Reading))%>%
  mutate(Depth_simple = floor(Sensor_depth))%>%
  group_by(Date,Depth_simple)%>%
  dplyr::summarize(Temp_C = mean(Reading),
            Depth_m = mean(Sensor_depth))%>%
  arrange(Date,Depth_m)%>%
  group_by(Date)%>%
  filter((Depth_m-lag(Depth_m)>.4)|(Depth_m-lag(Depth_m)<0)|is.na(lag(Depth_m)))%>%
  dplyr::summarize(buoy_freq = buoyancy.freq(Temp_C, Depth_m),
            Depth_m = attr(buoyancy.freq(Temp_C, Depth_m), 'depths'))

buoy_max = buoyancy_raw%>%
  group_by(Date)%>%
  dplyr::summarize(max = max(buoy_freq))
  
buoy_max$Date_22 = buoy_max$Date
year(buoy_max$Date_22)=2022

jpeg("./Figs/buoyancy_freq.jpg",res = 300, units = "in",width = 6, height = 4)
buoy_fig = buoy_max%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022))%>%
  ggplot(aes(x = Date_22, y= max, color = Year, fill = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  ylab("Buoyancy frequency")+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank(),
        legend.position = "none")
buoy_fig
dev.off()

surf = catwalk_format%>%
  group_by(Date)%>%
  dplyr::summarize(Reading = Reading[which.min(Sensor_depth)],
            Sensor_depth = 0,
            Reservoir_depth = unique(Reservoir_depth))
  
catwalk_format_with_zero = catwalk_format%>%
  full_join(surf)%>%
  arrange(Date,Sensor_depth)

vw_temp = c()
for(date in unique(catwalk_format_with_zero$Date)){
  temps = catwalk_format_with_zero%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  vw_temp = c(vw_temp, layer.temperature(top = min(baths$Depth_m), bottom = max(baths$Depth_m), wtr = temps$Reading, depths = temps$Sensor_depth, bthA = baths$SA_m2, bthD = baths$Depth_m))
}

vw_temp_df = data.frame(Date = unique(catwalk_format$Date), vw_temp = vw_temp)%>%
  mutate(Year = year(Date))
vw_temp_df$Date_22 = vw_temp_df$Date
year(vw_temp_df$Date_22)=2022

jpeg("./Figs/VW_temp_exo.jpg",res = 300, units = "in",width = 6, height = 4)
water = vw_temp_df%>%
  filter(Year %in% c(2021,2022),
         !is.na(vw_temp))%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = vw_temp, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Volume-weighted\nwater temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank(),
        legend.position = "none")
water
dev.off()

air_temp = read.csv("./Data/BVR_Air_Temp_2021_2022.csv")
air_temp_plot = air_temp%>%
  mutate(Year = year(DateTime),
         Air_Temp = Air_Temp_C_1,
         Date_22 = as.Date(DateTime))%>%
  filter(Year %in% c(2021,2022),
         !is.na(Air_Temp))%>%
  mutate(Year = as.factor(Year))%>%
  group_by(Date_22,Year)%>%
  summarize(Air_Temp = mean(Air_Temp))%>%
  arrange(Year,Date_22)
year(air_temp_plot$Date_22)=2022
library(zoo)
jpeg("./Figs/air_temp_exo.jpg",res = 300, units = "in",width = 6, height = 4)
air = air_temp_plot%>%
  ggplot(aes(x = Date_22, y = Air_Temp, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Air temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank())+
  #geom_line(aes(y=rollmean(Air_Temp, 10, fill = NA)), linewidth = 1)+
  #geom_line(aes(y=rollmean(Air_Temp, 10, fill = NA)), data = .%>%filter(Year==2022|Date_22>"2022-12-27"), linewidth = 0.3, color = "#00F7FF")+
  #geom_line(aes(y=rollmean(Air_Temp, 10, fill = NA)), data = .%>%filter(Year==2021|Date_22<"2022-1-03"), linewidth = 0.3, color = "grey50")+
  theme(legend.position = "none")
air
dev.off()

air_temp_plot%>%
  filter(Date_22>="2022-05-19"&Date_22<="2022-07-01")%>%
  group_by(Year)%>%
  summarize(mean = mean(Air_Temp),
            sd = sd(Air_Temp))

library(ggpubr)
jpeg("./Figs/air_and_water_temp.jpg",res = 300, units = "in",width = 6, height = 4)
ggarrange(air,water+ylim(min(air_temp_plot$Air_Temp),max(air_temp_plot$Air_Temp)), common.legend = T)
dev.off()

  
air_temp_plot$rol_mean = rollmean(air_temp_plot$Air_Temp,10,fill=NA,align = "right")
temp_dif = air_temp_plot%>%
  left_join(vw_temp_df%>%mutate(Year=as.factor(Year)))%>%
  mutate(dif_temp = vw_temp-rol_mean)%>%
  ggplot(aes(x = Date_22, y = dif_temp, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("VW water temperature minus\nrolling mean air temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")
temp_dif

jpeg("./Figs/temp_dif.jpg",res = 300, units = "in",width = 6, height = 4)
temp_dif
dev.off()

surf_plot = surf%>%
  mutate(Date_22 = Date,
         Year = year(Date))%>%
  filter(Year %in% c(2021,2022))
year(surf_plot$Date_22) = 2022

temp_dif_surf = air_temp_plot%>%
  left_join(surf_plot%>%mutate(Year=as.factor(Year)))%>%
  mutate(dif_temp = Reading-Air_Temp)%>%
  ggplot(aes(x = Date_22, y = dif_temp, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Water temperature minus\nrolling mean air temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")
temp_dif_surf

jpeg("./Figs/surface_temp.jpg",res = 300, units = "in",width = 6, height = 4)
surf_plot_save = surf_plot%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Reading, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Surface water temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank())+
  theme(legend.position = "none")
dev.off()

legend = get_legend(surf_plot_save)
library(cowplot)
jpeg("./Figs/physics_all.jpg",res = 300, units = "in",width = 8, height = 6)
plot_grid(air,surf_plot_save,water,buoy_fig,schmidt_fig,legend, align = "hv",labels = list("a","b","c","d","e",""),nrow=2,ncol=3,axis = "rltb")
dev.off()

bot = catwalk_format%>%
  group_by(Date)%>%
  dplyr::summarize(Reading = Reading[which.max(Sensor_depth)])%>%
  mutate(Date_22 = Date,
         Year = year(Date))%>%
  filter(Year %in% c(2021,2022))%>%
  mutate(Year = as.factor(Year))
year(bot$Date_22) = 2022

jpeg("./Figs/hypo_temp.jpg",res = 300, units = "in",width = 6, height = 4)
bot%>%
  ggplot(aes(x = Date_22, y = Reading, fill = Year, color = Year))+
  geom_point(shape = 21, stroke = .5, size = 1.5)+
  scale_fill_manual(values = c("black","#00F7FF"))+
  scale_color_manual(values = c("black","#0800FA"))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Bottom water temperature (ºC)")+
  theme_bw()+
  scale_x_date(date_breaks = "2 month", date_labels =  "%b")+
  theme(axis.title.x = element_blank())
dev.off()

flexible_bathy%>%
  filter(Date %in% as.Date(c("2022-05-19","2022-07-01")))%>%
  ggplot(aes(x = SA_m2,y=Depth_m))+
  geom_line()+
  scale_y_reverse()+
  facet_wrap(~Date)

surf%>%
  rename(surf_temp = Reading)%>%
  select(-Sensor_depth,-Reservoir_depth)%>%
  left_join(bot%>%rename(bot_temp=Reading))%>%
  mutate(Year=year(Date))%>%
  filter(month(Date)>7)%>%
  group_by(Year)%>%
  arrange(Date)%>%
  summarize(turnover=first(Date[surf_temp-bot_temp<1]))

yday("2022-11-6")-yday("2021-10-19")
```


Lots of extraneous metalimnion code I'm no longer using
```{r}
meta_depths_raw = catwalk_format%>%
  mutate(Depth_simple = round(Sensor_depth))%>%
  group_by(Date,Depth_simple)%>%
  dplyr::summarize(Temp_C = mean(Reading),
            Depth_m = mean(Sensor_depth),
            Reservoir_depth = mean(Reservoir_depth))%>%
  group_by(Date)%>%
  dplyr::summarize(epi_depth = meta.depths(Temp_C, Depth_m)[1],
            hypo_depth = meta.depths(Temp_C, Depth_m)[2],
            max_depth = max(Depth_m),
            min_depth = min(Depth_m),
            Reservoir_depth = mean(Reservoir_depth))

meta_depths = meta_depths_raw%>%
  filter(!epi_depth == hypo_depth)%>%
  dplyr::select(-max_depth, -min_depth)%>%
  filter(!abs(lag(epi_depth)-epi_depth)>3,
         !abs(lead(epi_depth)-epi_depth)>3,
         !abs(lag(hypo_depth)-hypo_depth)>3,
         !abs(lead(hypo_depth)-hypo_depth)>3)%>%
  pivot_longer(c(epi_depth,hypo_depth))

meta_depths$Date_22 = meta_depths$Date
year(meta_depths$Date_22)=2022

jpeg("./Figs/meta_depths.jpg",res = 300, units = "in",width = 6, height = 4)
meta_depths%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<9)%>%
  ggplot(aes(x = Date_22, y = value, color = Year))+
  geom_point()+
  geom_line()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  facet_wrap(~name)+
  ylab("Depth (m)")+
  xlab("")+
  theme_bw()
dev.off()


jpeg("./Figs/res_diagram_layers.jpg",res = 300, units = "in",width = 6, height = 4)
meta_depths_raw%>%
  filter(!epi_depth == hypo_depth)%>%
  dplyr::select(-min_depth)%>%
  filter(!abs(lag(epi_depth)-epi_depth)>3,
         !abs(lead(epi_depth)-epi_depth)>3,
         !abs(lag(hypo_depth)-hypo_depth)>3,
         !abs(lead(hypo_depth)-hypo_depth)>3)%>%
  mutate(hypo_width = max_depth-hypo_depth,
         meta_width = hypo_depth-epi_depth)%>%
  dplyr::select(Date,epi_depth,hypo_width,meta_width)%>%
  pivot_longer(c(epi_depth,hypo_width,meta_width))%>%
  mutate(Year = as.factor(year(Date)),
         name = factor(name, levels = c("epi_depth","meta_width","hypo_width")))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<9)%>%
  ggplot(aes(x = Date, y = value, fill = name))+
    geom_area()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  facet_wrap(~Year, scales = "free_x")+
  theme_bw()
dev.off()

meta_ratio = flexible_bathy%>%
  left_join(meta_depths%>%pivot_wider(names_from = name, values_from = value))%>%
  filter(!is.na(epi_depth),
         !is.na(hypo_depth))%>%
  group_by(Date)%>%
  dplyr::summarize(depth_above_epi = max(Depth_m[Depth_m<(epi_depth)]),
            epi_and_below = sum(Volume_L[Depth_m<=depth_above_epi]),
            correction = (1-(epi_depth-depth_above_epi))*Volume_L[Depth_m==depth_above_epi],
            epi_volume = epi_and_below-correction,
            depth_above_hypo = max(Depth_m[Depth_m<(hypo_depth)]),
            hypo_and_above = sum(Volume_L[Depth_m>=depth_above_hypo]),
            correction_hypo = unique(hypo_depth-depth_above_hypo)*Volume_L[Depth_m==depth_above_hypo],
            hypo_volume = hypo_and_above-correction_hypo,
            epi_hypo_ratio = epi_volume/hypo_volume
  )

meta_ratio$Date_22 = meta_ratio$Date
year(meta_ratio$Date_22) = 2022

jpeg("./Figs/epi_meta_ratio.jpg",res = 300, units = "in",width = 6, height = 4)
meta_ratio%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<10)%>%
  ggplot(aes(x = Date_22, y= epi_hypo_ratio, color = Year))+
  geom_point()+
  geom_smooth()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  ylab("Ratio of epilimnetic volume:hypolimnetic volume")+
  xlab("")
dev.off()
  

thermo_raw = catwalk_format%>%
  filter(!is.na(Reading))%>%
  mutate(Depth_simple = floor(Sensor_depth))%>%
  group_by(Date,Depth_simple)%>%
  dplyr::summarize(Temp_C = mean(Reading),
            Depth_m = mean(Sensor_depth),
            Reservoir_depth = mean(Reservoir_depth))%>%
  arrange(Date,Depth_m)%>%
  group_by(Date)%>%
  filter((Depth_m-lag(Depth_m)>.4)|(Depth_m-lag(Depth_m)<0)|is.na(lag(Depth_m)))%>%
  dplyr::summarize(thermo = thermo.depth(Temp_C, Depth_m),
            Reservoir_depth = mean(Reservoir_depth))
  
thermo_raw$Date_22 = thermo_raw$Date
year(thermo_raw$Date_22)=2022

write.csv(thermo_raw%>%select(-Date_22),"./Data/thermocline_depth.csv", row.names = F)

jpeg("./Figs/thermocline_depth.jpg",res = 300, units = "in",width = 6, height = 4)
thermo_raw%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<9)%>%
  ggplot(aes(x = Date_22, y= thermo, color = Year))+
  geom_point()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  #scale_y_reverse()+
  theme_bw()+
  ylab("Thermocline depth (m)")+
  xlab("")
dev.off()


meta_ratio = flexible_bathy%>%
  left_join(thermo_raw)%>%
  filter(!is.na(thermo))%>%
  group_by(Date)%>%
  dplyr::summarize(depth_above_thermo = max(Depth_m[Depth_m<(thermo)]),
            thermo_and_just_below = sum(Volume_L[Depth_m<=depth_above_thermo]), #1m layers
            correction_thermo = unique(1-(thermo-depth_above_thermo))*Volume_L[Depth_m==depth_above_thermo],
            depth_above_water = Depth_m[Depth_m<0],
            correction_surf = abs(unique(depth_above_water))*Volume_L[Depth_m==depth_above_water],
            epi_volume = thermo_and_just_below-correction_thermo-correction_surf,
            hypo_and_above = sum(Volume_L[Depth_m>=depth_above_thermo]),
            correction_hypo = unique(thermo-depth_above_thermo)*Volume_L[Depth_m==depth_above_thermo],
            hypo_volume = hypo_and_above-correction_hypo,
            epi_hypo_ratio = epi_volume/hypo_volume
  )

meta_ratio$Date_22 = meta_ratio$Date
year(meta_ratio$Date_22) = 2022

jpeg("./Figs/epi_hypo_ratio.jpg",res = 300, units = "in",width = 6, height = 4)
meta_ratio%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<10)%>%
  ggplot(aes(x = Date_22, y= epi_hypo_ratio, color = Year))+
  geom_point()+
  geom_smooth()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  ylab("Ratio of epilimnetic volume:hypolimnetic volume")+
  xlab("")
dev.off()

meta_ratio%>%
  dplyr::select(Date,epi_volume,hypo_volume,Date_22)%>%
  mutate(Year=year(Date))%>%
  pivot_longer(cols = c(epi_volume,hypo_volume))%>%
  mutate(Volume_m3 = value/1000)%>%
  filter(month(Date)==7&day(Date)==1|
           month(Date)==5&day(Date)==19)%>%
  group_by(Year,name)%>%
  summarize(vol_pre = Volume_m3[month(Date)==5],
            vol_post = Volume_m3[month(Date)==7],
            change_m3 = vol_pre-vol_post,
            pct = change_m3/vol_pre*100)

214569.9/310975.5562 #loss of epi volume / total volume loss

jpeg("./Figs/Vol_split_2022vs2021.jpeg",width = 6, height = 4, units = "in", res = 300)
meta_ratio%>%
  mutate(Year=as.factor(year(Date)))%>%
  filter(!Year==2020,
         month(Date)>4,
         month(Date)<11)%>%
  dplyr::select(Date_22, Year, epi_volume,hypo_volume)%>%
  pivot_longer(cols = c(epi_volume,hypo_volume))%>%
  ggplot(aes(x = Date_22,y=value, color = Year))+
  geom_line()+
  facet_wrap(~name)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme(axis.title.x = element_blank())+
  ylab("Volume")
dev.off()

jpeg("./Figs/Vol_filled_2022vs2021.jpeg",width = 4.5, height = 4.5, units = "in", res = 300)
meta_ratio%>%
  mutate(Year=as.factor(year(Date)))%>%
  filter(!Year==2020,
         month(Date)>=5,
         month(Date)<10)%>%
  dplyr::select(Date_22, Year, epi_volume,hypo_volume)%>%
  pivot_longer(cols = c(epi_volume,hypo_volume))%>%
  mutate(name = ifelse(name=="epi_volume","Epilimnetic volume","Hypolimnetic volume"),
         name = factor(name,levels = c("Epilimnetic volume","Hypolimnetic volume")))%>%
  ggplot(aes(x = Date_22, y = value/1000, fill = name))+
  scale_fill_manual(values = c("#77c7fc","#104466"))+
  geom_area()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  facet_grid(rows = ~Year, scales = "free_x", space = "free_x")+
  theme_bw()+
  ylab("Volume (m3)")+
  theme(axis.title.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
dev.off()
```


```{r}
jpeg("./Figs/res_diagram_layers_thermo.jpg",res = 300, units = "in",width = 6, height = 4)
thermo_raw%>%
  filter(!thermo == Reservoir_depth)%>%
  mutate(hypo_width = Reservoir_depth-thermo)%>%
  dplyr::select(Date,thermo,hypo_width)%>%
  rename(epi_width = thermo)%>%
  pivot_longer(c(epi_width,hypo_width))%>%
  mutate(Year = as.factor(year(Date)),
         name = factor(name, levels = c("epi_width","hypo_width")))%>%
  filter(Year %in% c(2021,2022),
         month(Date)>4,
         month(Date)<10)%>%
  ggplot(aes(x = Date, y = value, fill = name))+
  geom_area()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  facet_grid(rows = ~Year, scales = "free_x", space = "free_x")+
  theme_bw()+
  ylab("Height above sediments (m)")
dev.off()
```



Lake number
```{r}
layer_dens = c()
dates = c()
for(date in unique(catwalk_format$Date)){
  temps = catwalk_format%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  thermo = thermo_raw%>%
    filter(Date == date)
  if(!is.na(thermo$thermo)){
    layer_dens = c(layer_dens, 
                   layer.density(top = 0, 
                                 bottom = thermo$thermo, 
                                 wtr = temps$Reading, 
                                 depths = temps$Sensor_depth, 
                                 bthA = baths$SA_m2, 
                                 bthD = c(0,baths$Depth_m[2:length(baths$Depth_m)])))
    dates = c(dates, date)
  }
}

dens_df = data.frame(Date = dates, Density = layer_dens)%>%
  mutate(Date = as.Date(Date, origin = "1970-01-01"),
         Year = year(Date))




met = read.csv("./Data/FCRmet.csv", skip = 1)

met1 = met%>%
  filter(nchar(TIMESTAMP)>3)%>%
  mutate(Date = as.Date(as.POSIXct(TIMESTAMP)))%>%
  group_by(Date)%>%
  dplyr::summarize(wind = mean(as.numeric(WS_ms_Avg)))

met_dens_comb = met1%>%
  left_join(dens_df)%>%
  filter(!is.na(Density))

met_dens_comb$uStar = uStar(wndSpeed = met_dens_comb$wind, 
                            wndHeight = 2.4,#Adrienne's approximation
                            averageEpiDense = met_dens_comb$Density)



hypo_dens = c()
dates = c()
for(date in unique(catwalk_format$Date)){
  temps = catwalk_format%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  thermo = thermo_raw%>%
    filter(Date == date)
  if(!is.na(thermo$thermo)){
    hypo_dens = c(hypo_dens, 
                  layer.density(top = thermo$thermo, 
                                bottom = max(baths$Depth_m), 
                                wtr = temps$Reading, 
                                depths = temps$Sensor_depth, 
                                bthA = baths$SA_m2, 
                                bthD = c(baths$Depth_m)))
    dates = c(dates, date)
  }
}

hypo_dens_df = data.frame(Date = dates, Density = hypo_dens)%>%
  mutate(Date = as.Date(Date, origin = "1970-01-01"),
         Year = year(Date))




lake_num = c()
dates = c()
for(date in unique(catwalk_format$Date)){
  baths = flexible_bathy%>%
    filter(Date==date)
  uStar_calc = met_dens_comb%>%
    filter(Date == date)
  meta = meta_depths%>%
    pivot_wider()%>%
    filter(Date == date)
  St_calc = schmidt_df%>%
    filter(Date==date)
  hypo = hypo_dens_df%>%
    filter(Date==date)

  num = lake.number(bthA = baths$SA_m2, 
                    bthD = baths$Depth_m,
                    uStar = uStar_calc$uStar,
                    St = St_calc$Schmidt,
                    metaT = meta$epi_depth,
                    metaB = meta$hypo_depth,
                    averageHypoDense = hypo$Density
                    )
  if(!is_empty(num)){
    dates = c(dates, date)
    lake_num = c(lake_num, num)
  }
  
}

lake_number_df = data.frame(Date = dates, lake_num = lake_num)%>%
  mutate(Date = as.Date(Date, origin = "1970-01-01"),
         Year = year(Date))

lake_number_df$Date_22 = lake_number_df$Date
year(lake_number_df$Date_22)=2022

jpeg("./Figs/Lake number.jpg",res = 300, units = "in",width = 6, height = 4)
lake_number_df%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = lake_num, color = Year))+
  geom_point()+
  geom_smooth()+
  ylab("Lake number")+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()
```


Heatmap
```{r}
cat_long = read.csv("~/Desktop/github/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_BVRplatform/2022/BVR_longoutput_FLARE_2020_2021.csv")%>%
  filter(Sensor=="ThermistorTemp")

var = c("Reading") #Temp_C

filt_no_surf = cat_long%>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date),
         Height = Reservoir_depth-Sensor_depth,
         Rounded_depth_tenth = round(Height,1))%>%
  filter(!is.na(get(var)),
         Reservoir == "BVR")%>%
  ungroup()%>%
  dplyr::select(Date, Rounded_depth_tenth,Reading, Year)%>%
  group_by(Year, Date, Rounded_depth_tenth)%>%
  dplyr::summarize(Reading=mean(Reading, na.rm = T))%>%
  dplyr::rename(Sensor_depth = Rounded_depth_tenth)

surf = cat_long%>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date))%>%
  group_by(Date, Year)%>%
  dplyr::summarize(Reading = Reading[which.min(Sensor_depth)],
            Sensor_depth = mean(Reservoir_depth))

bottom = cat_long%>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date))%>%
  group_by(Date, Year)%>%
  dplyr::summarize(Reading = Reading[which.max(Sensor_depth)],
            Sensor_depth = 0)
  
filt = filt_no_surf%>%
  full_join(surf)%>%
  full_join(bottom)

depth_sum = cat_long%>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date))%>%
  filter(Reservoir == "BVR")%>%
  ungroup()%>%
  dplyr::select(Date, Reservoir_depth,Year)%>%
  group_by(Year, Date)%>%
  dplyr::summarize(Reservoir_depth=mean(Reservoir_depth, na.rm = T))%>%
  ungroup()%>%
  filter(!Year == 2020)%>%
  mutate(max = max(Reservoir_depth))

light = read.csv("./Data/attenuation_calc.csv")%>%
  mutate(Date = as.Date(Date))%>%
  left_join(depth_sum)

Years = c(2021,2022)
interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
for(year in Years){
    bvr<- filt%>%
      filter(Year == year)%>%
      ungroup()%>%
      dplyr::mutate(random = sample(1:n(),n()))%>%
      arrange(random)
    
    if(nrow(bvr)>0){
      bvr_interp <- interp2xyz(interp(bvr$Date,bvr$Sensor_depth,bvr[[var]],xo = seq(min(bvr$Date), max(bvr$Date), 1),yo = seq(min(bvr$Sensor_depth), max(bvr$Sensor_depth), by = .05), duplicate = "mean"),data.frame = T)
      interp = interp%>%
        full_join(bvr_interp)
    }
    
}

sensor_depth_plot = filt_no_surf%>%
  filter(Year%in% c(2021,2022))%>%
  group_by(Date)%>%
  filter(length(unique(Sensor_depth))<=11)%>%
  ungroup()%>%
  select(Year,Sensor_depth)%>%
  unique()%>%
  mutate(Date=as.Date(paste0(Year,"-01-01")))

#Heatmap
jpeg(paste0("./Figs/BVR_catwalk_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
p = interp%>%
  mutate(x = as.Date(x, origin = "1970-01-01"),
         Year = year(x))%>%
  filter(!is.na(z))%>%
  ggplot()+
  geom_raster(aes(x=x, y=y,fill = z))+
  geom_ribbon(data = depth_sum, aes(x = Date, ymin= Reservoir_depth, ymax = max), fill = "white", color = "black",lwd=.2)+
  #geom_line(data = thermo_raw%>%
  #            mutate(Year=year(Date))%>%
  #            filter(Year%in%c(2021,2022)), aes(x = Date, y = Reservoir_depth - thermo))+
  geom_line(data = light%>%
              mutate(Year=year(Date))%>%
              filter(Year%in%c(2021,2022)), aes(x = Date, y = Reservoir_depth-Zeu, color = "Euphotic zone"))+
  scale_color_manual(values = "black")+
  #geom_line(data = meta_depths%>%mutate(Year=year(Date))%>%
  #            filter(Year%in%c(2021,2022)), aes(x = Date, y = Reservoir_depth -value, group = name), lty = "dashed")+
  labs(y = "Height above sediments (m)")+
  scale_x_date(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  theme(panel.border = element_rect(fill = NA),
        axis.title.x=element_blank())+
  facet_grid(cols = vars(Year),
             scales = "free",
             space = "free"
             )+
  labs(color = "")+
  geom_point(data = sensor_depth_plot, aes(x = Date, y = Sensor_depth), shape = 23, fill = "black", color = "white", size  =2.5)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_fill_gradientn(name = "Water temperature\n(°C)",
                       limits = c(-1, 30),
                       colours = c("#313695", "#4575b4", "#74add1",
                                   "#abd9e9", "#e0f3f8", "#ffffbf", "#fee090",
                                   "#fdae61", "#f46d43", "#d73027", "#a50026" ))
print(p)
dev.off()
```

Adding secchi to heatmap
```{r}
secchi = read_excel("./Data/2022_Secchi_depth.xlsx")

inUrl1  <- "https://pasta.lternet.edu/package/data/eml/edi/198/10/375f87747001e1681b0e805d00cc1341" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Secchi_m",     
                    "Flag_DateTime",     
                    "Flag_Secchi"    ), check.names=TRUE)%>%
   mutate(DateTime = as.Date(DateTime))
               
unlink(infile1)

secchi_plot = secchi%>%
  full_join(dt1)%>%
  mutate(Date=as.Date(DateTime))%>%
  filter(Reservoir == "BVR",
         Site == 50)%>%
  mutate(Year = year(Date),
         Date_22 = Date)
year(secchi_plot$Date_22)<- 2022

secchi_heatmap = secchi_plot%>%
  filter(Year %in% c(2021,2022))%>%
  full_join(depth_sum)%>%
  filter(!is.na(Secchi_m))%>%
  mutate(Secchi_height = Reservoir_depth-Secchi_m)

p+
  geom_line(aes(x = Date, y = Secchi_height), data = secchi_heatmap, size = 2, color = "darkgreen")+
  geom_line(aes(x = Date, y = Secchi_height), data = secchi_heatmap, color = "white")
  
```


2021 vs 2022 depth
```{r}
cat_long = read.csv("~/Desktop/github/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_BVRplatform/2022/BVR_longoutput_FLARE_2020_2021.csv")

depths = cat_long%>%
  mutate(Date = as.Date(DateTime))%>%
  group_by(Date)%>%
  dplyr::summarize(Depth_m = mean(Reservoir_depth))%>%
  mutate(Year = year(Date))
depths$Date_22 = depths$Date
year(depths$Date_22)=2022

jpeg(paste0("./Figs/Depth2022vs2021.jpeg"),width = 8, height = 4, units = "in", res = 300)
depths%>%
  filter(Year %in% c(2021,2022))%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Depth_m, color = Year))+
  geom_line()+
  theme_bw()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme(axis.title.x = element_blank())+
  ylab("Reservoir Depth (m)")+
  geom_point(aes(x=as.Date("2022-06-01"),y=0), alpha = 0)
dev.off()
```

2021 vs 2022 volume
```{r}
bathy = read.csv("./Data/Bathymetry_comb.csv")%>%
  filter(Reservoir == "BVR")

cat_long = read.csv("~/Desktop/github/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_BVRplatform/2022/BVR_longoutput_FLARE_2020_2021.csv")

depths = cat_long%>%
  mutate(Date = as.Date(DateTime))%>%
  group_by(Date)%>%
  dplyr::summarize(Reservoir_depth = mean(Reservoir_depth))%>%
  mutate(Year = year(Date))

flexible_bathy = depths%>%
  mutate(Reservoir = "BVR")%>%
  full_join(bathy)%>%
  group_by(Date)%>%
  mutate(Depth_m = Depth_m - (max(Depth_m)-unique(Reservoir_depth)) + 1)%>%
  filter(Depth_m>=-1)

vol_sum = flexible_bathy%>%
  group_by(Date)%>%
  dplyr::summarize(depth_above_water = Depth_m[Depth_m<0],
            total_plus = sum(Volume_L[Depth_m>0]),
            correction = (1-abs(unique(depth_above_water)))*Volume_L[Depth_m==depth_above_water],
            total = total_plus+correction)%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year %in% c(2021,2022))

to_export_vol = vol_sum%>%
  dplyr::select(Date, total)%>%
  rename(Volume_L = total)%>%
  mutate(Reservoir = "BVR")

to_export_vol%>%
  filter(month(Date)==7&day(Date)==1|
           month(Date)==5&day(Date)==19)%>%
  mutate(Year = year(Date),
         Volume_m3 = Volume_L/1000)%>%
  group_by(Year)%>%
  summarize(vol_pre = Volume_m3[month(Date)==5],
            vol_post = Volume_m3[month(Date)==7],
            change_m3 = vol_pre-vol_post,
            pct = change_m3/vol_pre*100)

write.csv(to_export_vol, "./Data/BVR_volume_exported.csv", row.names = F)

vol_sum$Date_22 = vol_sum$Date
year(vol_sum$Date_22)=2022

jpeg(paste0("./Figs/Vol2022vs2021.jpeg"),width = 8, height = 4, units = "in", res = 300)
vol_sum%>%
  ggplot(aes(x = Date_22, y = total, color = Year))+
  geom_line()+
  geom_point(aes(x=as.Date("2022-06-01"),y=0), alpha = 0)+
  ylab("Reservoir volume")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()
```

