---
title: "YSI_inspection_2013_2023"
author: "Austin Delany"
date: "2023-12-08"
output: html_document
---

This script is the data visualization script that:
1) reads in YSI data from the most recent year (current_file)
2) reads in YSI data from the most recent EDI data publication (historic_file)
3) combines the current and historic data
4) reprocesses historic data using the L1 qaqc script
5) generates figures to visualize both this past year and all combined years of data


```{r setup packages, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Add the names of the packages 
pacman::p_load(tidyverse, lubridate, gsheet)
```

```{r read in current and historic data}
current_file <- read_csv('~/Reservoirs/Data/DataNotYetUploadedToEDI/YSI_PAR/ysi_L1.csv', col_types = cols())
#note that this file path doesn't not work for HLW - need to replace "~/Reservoirs" with "."
#and make sure knit directory is set to project directory

historic_file <- read_csv('https://portal.edirepository.org/nis/dataviewer?packageid=edi.198.11&entityid=6e5a0344231de7fcebbe6dc2bed0a1c3', col_types = cols())
```

```{r combine current and historic data if needed}
profiles <- bind_rows(current_file, historic_file)
```

```{r}
#source L1 functin to run all data through QAQC process
source("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Scripts/L1_functions/ysi_create.R")

profiles_cleaned <- ysi_qaqc(data_file = profiles,
            gsheet_data = FALSE,
            maintenance_file = 'https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Data/DataNotYetUploadedToEDI/YSI_PAR/maintenance_log.csv',
            outfile = NULL)
```

```{r add additional columns}
#### YSI diagnostic plots #### 
profiles_long <- profiles_cleaned |>
  ungroup() |>
  mutate(year = year(DateTime)) |> 
  select(-c(ORP_mV:Flag_pH)) |>
  gather(metric, value, c(Temp_C:PAR_umolm2s)) 

#value as numeric
profiles_long$value<- as.numeric(profiles_long$value)
profiles_long$Depth_m<- as.numeric(profiles_long$Depth_m)
```

```{r}
# Plot ORP as a function of DO
ggplot(subset(profiles, Reservoir == "BVR" | Reservoir=="FCR"), aes(x = DO_mgL, y = ORP_mV, col = Reservoir)) + 
  geom_point() + 
  facet_grid(Reservoir ~., scales= 'free_y')
```

```{r}
# Plot all values
ggplot(profiles_long, aes(x = DateTime, y = value, col=Reservoir)) +
  geom_point(size=1) +
  stat_summary(fun="mean", geom="point",pch=21,  size=3, fill='black') +
  facet_grid(metric ~ Reservoir, scales= 'free_y') +
  scale_x_datetime("Date", date_breaks="1 year", date_labels = "%Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='none')
```

```{r}
# Deep hole time series for BVR
ggplot(subset(profiles_long, Site=="50" & Reservoir=="BVR"), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_wrap(~metric, scales='free') +
  scale_x_datetime("Date", date_breaks="1 year", date_labels = "%Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/YSI_depths_2023_bvr.jpg"),width=3.5, height=4)
```
```{r}
# Deep hole time series for FCR
ggplot(subset(profiles_long, Site=="50" & Reservoir=="FCR"), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_wrap(~metric, scales='free') +
  scale_x_datetime("Date", date_breaks="1 year", date_labels = "%Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/YSI_depths_2023_fcr.jpg"),width=3.5, height=4)
```

```{r}
# Deep hole time series for CCR
ggplot(subset(profiles_long, Site=="50" & Reservoir=="CCR"), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_wrap(~metric, scales='free') +
  scale_x_datetime("Date", date_breaks="1 year", date_labels = "%Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/YSI_depths_2023_ccr.jpg"),width=3.5, height=4)
```

```{r}
# FCR only; all sampling sites 
ggplot(subset(profiles_long, Reservoir=='FCR'), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Site, scales='free') +
  scale_x_datetime("Date", date_breaks="1 year", date_labels = "%Y") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/FCR_YSIbySite_2023.jpg"),width=3.5, height=4)
```

```{r}
#just look at current year - fcr
ggplot(subset(profiles_long, Reservoir=="FCR" & year(DateTime) %in% c(2023)), 
       aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Site, scales='free') +
  scale_x_datetime("Date", date_breaks="1 month", date_labels = "%b %Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/FCR_YSI_depths_2023_fcr.jpg"),width=3.5, height=4)
```

```{r}
#just look at current year - bvr (just temp)
ggplot(subset(profiles_long,Reservoir=="BVR" & year(DateTime) %in% c(2023)), 
       aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Site, scales='free') +
  scale_x_datetime("Date", date_breaks="1 month", date_labels = "%b %Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/BVR_YSI_depths_2023_fcr.jpg"),width=3.5, height=4)
```

```{r}
#just look at current year - ccr
ggplot(subset(profiles_long, Reservoir=="CCR" & year(DateTime) %in% c(2023)), 
       aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Site, scales='free') +
  scale_x_datetime("Date", date_breaks="1 month", date_labels = "%b %Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Figures/CCR_YSI_depths_2023_fcr.jpg"),width=3.5, height=4)
```

```{r}
#drop rows with NAs across all variables
profiles_cleaned <- profiles_cleaned |> 
  filter(!if_all(c(Temp_C:pH), is.na))
```


```{r save the data}
write.csv(profiles_cleaned,file.path("./Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Data/YSI_PAR_profiles_2013-2023.csv"), row.names=FALSE)
```


```{r}
# Maintenance Log
download.file("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Data/DataNotYetUploadedToEDI/YSI_PAR/maintenance_log.csv", "Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_Secchi/2023/Data/YSI_maintenancelog_2013_2023.csv")

# qaqc function
download.file("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Scripts/L1_functions/ysi_create.R", "Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_Secchi/2023/Data/YSI_qaqc_2023_2023.R")
```
