---
title: "Drawdown metals"
author: "Abby Lewis"
date: "7/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(lubridate)
library(akima)
library(colorRamps)
library(LakeMetabolizer)
```

Heatmaps (2022)
```{r}
#ghg = read_excel("GHG_MEGA_GC_SHEET_EXCEL_2022.xlsx", sheet =2, skip = 9)
ghg = read.csv("GHG_MEGA_GC_SHEET_EXCEL_2022.csv", skip = 9)
ghg = ghg[c(1,2,3,4,14,15)]
colnames(ghg)= c("DateTime","Site","Depth_m","Reservoir","ch4_umolL","co2_umolL")
ghg = ghg%>%
  mutate(Site = as.numeric(Site),
         ch4_umolL = as.numeric(ch4_umolL),
         co2_umolL = as.numeric(co2_umolL))%>%
  mutate(Site = ifelse(Site == 1,40,Site))

vars = c("co2_umolL","ch4_umolL")
for(var in vars){
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  Sites = c(40,50)
  for(site in Sites){
    bvr<- ghg%>%
      mutate(Date = as.Date(DateTime),
             Year = year(Date))%>%
      filter(Site == site,
             Reservoir == "BVR",
             !is.na(get(var)))
    bvr_interp <- interp2xyz(interp(bvr$Date,bvr$Depth_m,bvr[[var]],xo = seq(min(bvr$Date), max(bvr$Date), .1),yo = seq(min(bvr$Depth_m), max(bvr$Depth_m), by = .01), duplicate = "mean"),data.frame = T)
    interp = interp%>%
      full_join(bvr_interp%>%mutate(Site=site))
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  #Heatmap
  jpeg(paste0("./Drawdown Figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot(aes(x=x, y=y))+
    geom_raster(aes(fill = z))+
    scale_y_reverse(expand = c(0,0))+
    labs(x = "", y = "Depth (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(blue2green2red(100))}else{blue2green2red(100)}, na.value="gray", name = var)+
    scale_x_date(expand = c(0,0))+
    theme(panel.border = element_rect(fill = NA))+
    facet_grid(rows= vars(Site),
               cols = vars(Year),
               scales = "free",
               space = "free"
               )
  print(p)
  dev.off()
}
```

Combined with historical data
```{r}
#Update to pull from EDI when ready


ghg = read.csv("Dissolved_GHG_2015_2022.csv")
ghg = ghg%>%
  mutate(Site = as.numeric(Site),
         ch4_umolL = as.numeric(CH4_umolL),
         co2_umolL = as.numeric(CO2_umolL))%>%
  mutate(DateTime=as.Date(DateTime),
         Date_22 = DateTime,
         Year = year(DateTime))
year(ghg$Date_22)=2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg(paste0("./Drawdown Figs/BVR_weir_co2_2021_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
ghg%>%
  filter(Site==100,
         year(DateTime)%in%c(2021,2022))%>%
  ggplot(aes(x = Date_22, y = co2_umolL, color = as.factor(Year)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  geom_point()+
  geom_line()+
  ylab("CO2 (umolL)")+
  theme(axis.title.x = element_blank())
dev.off()

jpeg(paste0("./Drawdown Figs/BVR_0.1m_co2_2021_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
ghg%>%
  filter(Site==50,
         Depth_m ==0.1,
         Reservoir=="BVR",
         year(DateTime)%in%c(2021,2022),
         !is.na(co2_umolL))%>%
  ggplot(aes(x = Date_22, y = co2_umolL, color = as.factor(Year)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  geom_point()+
  ylab("CO2 (umolL)")+
  theme(axis.title.x = element_blank())
dev.off()

jpeg(paste0("./Drawdown Figs/BVR_weir_ch4_2021_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
ghg%>%
  filter(Site==100,
         year(DateTime)%in%c(2021,2022))%>%
  ggplot(aes(x = Date_22, y = ch4_umolL, color = as.factor(Year)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  geom_point()+
  geom_line()+
  ylab("CH4 (umolL)")+
  theme(axis.title.x = element_blank())
dev.off()

jpeg(paste0("./Drawdown Figs/BVR_0.1_ch4_2021_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
ghg%>%
  filter(Site==50,
         Depth_m ==0.1,
         Reservoir=="BVR",
         year(DateTime)%in%c(2021,2022),
         !is.na(ch4_umolL))%>%
  ggplot(aes(x = Date_22, y = ch4_umolL, color = as.factor(Year)))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  geom_point()+
  ylab("CH4 (umolL)")+
  theme(axis.title.x = element_blank())
dev.off()

export = ghg%>%
  filter(Site==50,
         Depth_m ==0.1,
         Reservoir=="BVR",
         year(DateTime)%in%c(2020,2021,2022),
         CH4_umolL<5)%>%#Removing one erroneous 2021 point
  group_by(DateTime)%>%
  summarize(ch4_umolL=mean(ch4_umolL, na.rm = T),
            co2_umolL=mean(co2_umolL, na.rm = T))

write.csv(export,"../../BVR drawdown/Data/GHG at 0.1m.csv")

vars = c("co2_umolL","ch4_umolL")
Years = c(2021,2022)
Sites = c(40,50)
for(var in vars){
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  for(site in Sites){
    for(year in (Years)){
      bvr<- ghg%>%
        mutate(Date = as.Date(DateTime),
               Year = year(Date))%>%
        filter(Site == site,
               Year == year,
               Reservoir == "BVR",
               !is.na(get(var)),
               year(DateTime)%in%c(2021,2022))%>%
        arrange(co2_umolL)
      if(nrow(bvr)>0){
        bvr_interp <- interp2xyz(interp(bvr$Date,bvr$Depth_m,bvr[[var]],xo = seq(min(bvr$Date), max(bvr$Date), .1),yo = seq(min(bvr$Depth_m), max(bvr$Depth_m), by = .01), duplicate = "mean"),data.frame = T)
        interp = interp%>%
          full_join(bvr_interp%>%mutate(Site=site))
      }
    }
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  #Heatmap
  jpeg(paste0("./Drawdown Figs/BVR_",var,"_heatmap_2021_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot(aes(x=x, y=y))+
    geom_raster(aes(fill = z))+
    scale_y_reverse(expand = c(0,0))+
    labs(x = "", y = "Depth (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(blue2green2red(100))}else{blue2green2red(100)}, na.value="gray", name = var)+
    scale_x_date(expand = c(0,0))+
    theme(panel.border = element_rect(fill = NA))+
    facet_grid(cols= vars(Site),
               rows = vars(Year),
               scales = "free",
               space = "free"
               )
  print(p)
  dev.off()
}

```

```{r}
ugga = read_csv("../../UGGA/UGGA_Raw/2022/TextFiles/2022_season_Flux_Output.csv")%>%
  mutate(Date = as.Date(Date))

ugga%>%
  ggplot(aes(x = Date_real, y = co2_flux_umolCm2s))+
  geom_point()+
  facet_wrap(~Site)+
  geom_smooth()+
  theme(axis.title.x = element_blank())

jpeg("./Drawdown Figs/BVR_methane_emission.jpg", res = 300, width = 4, height = 4, units = "in")
ugga%>%
  group_by(Date_real,Site)%>%
  summarize(mean=mean(ch4_flux_umolCm2s),
            sd = sd(ch4_flux_umolCm2s))%>%
  mutate(Site = ifelse(Site==1,40,Site))%>%
  ggplot(aes(x = Date_real))+
  geom_point(aes(y=mean), color = "blue")+
  geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd), color = "blue")+
  facet_grid(rows = vars(Site))+
  geom_line(aes(y=mean), color = "blue")+
  ylab("Methane emission (µmol/m2/s)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()

jpeg("./Drawdown Figs/BVR_co2_emission.jpg", res = 300, width = 4, height = 4, units = "in")
ugga%>%
  group_by(Date_real,Site)%>%
  summarize(mean=mean(co2_flux_umolCm2s),
            sd = sd(co2_flux_umolCm2s))%>%
  mutate(Site = ifelse(Site==1,40,Site))%>%
  ggplot(aes(x = Date_real))+
  geom_point(aes(y=mean), color = "blue")+
  geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd), color = "blue")+
  facet_grid(rows = vars(Site))+
  geom_line(aes(y=mean), color = "blue")+
  ylab("CO2 emission (µmol/m2/s)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()

ugga_sum = ugga%>%
              mutate(Site=ifelse(Site==1,40,Site))%>%
              group_by(Site,Date_real, Reservoir)%>%
              summarize(co2_flux_umolCm2s = mean(co2_flux_umolCm2s, na.rm = T),
                        ch4_flux_umolCm2s = mean(ch4_flux_umolCm2s, na.rm = T),
                        Temp_C = mean(Temp_C,na.rm = T))


ghg%>%
  filter(Depth_m==0.1,
         Reservoir == "BVR",
         Site %in% c(40,50))%>%
  group_by(Reservoir, Site, DateTime)%>%
  summarize(co2_umolL=mean(co2_umolL))%>%
  full_join(ugga_sum, by = c("Reservoir","Site", "DateTime"="Date_real"))%>%
  filter(!is.na(co2_flux_umolCm2s))%>%
  ggplot(aes(x = co2_umolL,y = co2_flux_umolCm2s, color = Temp_C, shape = as.factor(Site)))+
  geom_point()

ghg%>%
  filter(Depth_m==0.1,
         Reservoir == "BVR",
         Site %in% c(40,50),
         year(DateTime)%in%c(2022))%>%
  group_by(Reservoir, Site, DateTime)%>%
  summarize(ch4_umolL=mean(ch4_umolL))%>%
  full_join(ugga_sum, by = c("Reservoir","Site", "DateTime"="Date_real"))%>%
  ggplot(aes(x = ch4_umolL,y = ch4_flux_umolCm2s, color = Temp_C,shape = as.factor(Site)))+
  geom_point()

ghg_to_join = ghg%>%
  filter(Depth_m==0.1)%>%
  group_by(Reservoir, Site, DateTime)%>%
  summarize(ch4_umolL=mean(ch4_umolL),
            co2_umolL = mean(co2_umolL))%>%
  full_join(ugga_sum, by = c("Reservoir","Site", "DateTime"="Date_real"))%>%
  select(-Temp_C)
  

met = read.csv("./Other drawdown data/FCRmet.csv", skip = 1)%>%
  filter(nchar(TIMESTAMP)!=0,
         TIMESTAMP != "TS")

met_rename = met%>%
  rename(wnd = WS_ms_Avg,
         datetime = TIMESTAMP)%>%
  mutate(wnd = as.numeric(wnd))
u10 = wind.scale(met_rename, wnd.z = 2)
ts.data = rmv.vars(met_rename,"wnd", ignore.offset = T)
ts.data = merge(ts.data,u10)
k600_cole = k.cole(ts.data)

surface = read.csv("./Other drawdown data/CTD_surface.csv")%>%
  mutate(Date = as.Date(Date))

with_temp = k600_cole%>%
  mutate(datetime = as_datetime(datetime),
         Date = as.Date(datetime))%>%
  group_by(Date)%>%
  summarize(k600 = mean(k600))%>%
  full_join(surface)%>%
  filter(!is.na(Temp_C),
         !is.na(k600))%>%
  left_join(ghg_to_join%>%rename(Date=DateTime))

with_temp$GEV_co2 = k600.2.kGAS.base(with_temp$k600, with_temp$Temp_C, gas="CO2")
with_temp$flux_co2 = with_temp$GEV_co2*(412-with_temp$co2_umolL*44.1)
with_temp$GEV_ch4 = k600.2.kGAS.base(with_temp$k600, with_temp$Temp_C, gas="CH4")
with_temp$flux_ch4 = with_temp$GEV_ch4*(with_temp$co2_umolL*16.04-1.7)

with_temp%>%
  filter(!is.na(flux_co2),
         !is.na(co2_flux_umolCm2s))%>%
  ggplot(aes(x = flux_co2, y = co2_flux_umolCm2s))+
  geom_point()

with_temp%>%
  filter(!is.na(flux_ch4),
         !is.na(ch4_flux_umolCm2s))%>%
  ggplot(aes(x = flux_ch4, y = ch4_flux_umolCm2s))+
  geom_point()
```

