---
title: "GHG 50 vs 01 comparison"
author: "Abby Lewis"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
```

```{r}
#ghg = read_csv("final_GHG_2015-June2022.csv")
ghg = read_excel("GHG_MEGA_GC_SHEET_EXCEL_2022.xlsx", sheet =2, skip = 9)
ghg = ghg[c(1,2,3,4,14,15)]
colnames(ghg)= c("DateTime","Site","Depth_m","Reservoir","ch4_umolL","co2_umolL")
ghg = ghg%>%
  mutate(Site = as.numeric(Site),
         ch4_umolL = as.numeric(ch4_umolL),
         co2_umolL = as.numeric(co2_umolL))%>%
  mutate(Site = ifelse(Site == 1,40,Site))


ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40,50))%>%
  ggplot(aes(x = DateTime, y = Depth_m, color = ch4_umolL))+
  geom_point()+
  scale_y_reverse()+
  facet_wrap(~Site)

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40,50),
         Depth_m == 3)%>%
  ggplot(aes(x = DateTime, y = ch4_umolL, color = as.factor(Site)))+
  geom_point()+
  ggtitle("3 m")

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40,50),
         Depth_m == 0.1)%>%
  ggplot(aes(x = DateTime, y = ch4_umolL, color = as.factor(Site)))+
  geom_point()+
  ggtitle("0.1 m")

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40),
         Depth_m %in% c(4,3,0.1))%>%
  ggplot(aes(x = DateTime, y = ch4_umolL, color = as.factor(Depth_m)))+
  scale_color_discrete(name = "Depth (m)")+
  geom_point()+
  ggtitle("Site 01")

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40,50),
         Depth_m == 0.1)%>%
  ggplot(aes(x = DateTime, y = co2_umolL, color = as.factor(Site)))+
  geom_point()+
  ggtitle("0.1 m")

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(40),
         Depth_m %in% c(4,3,0.1))%>%
  ggplot(aes(x = DateTime, y = co2_umolL, color = as.factor(Depth_m)))+
  scale_color_discrete(name = "Depth (m)")+
  geom_point()+
  ggtitle("Site 01")


ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(50),
         Depth_m%in%c(0.1,3,6))%>%
  ggplot(aes(x = DateTime, y = ch4_umolL, color = as.factor(Depth_m)))+
  scale_color_discrete(name = "Depth (m)")+
  geom_point()+
  ggtitle("Site 50")

ghg%>%
  filter(year(DateTime)==2022,
         Reservoir == "BVR",
         Site %in% c(50),
         Depth_m%in%c(0.1,3,6))%>%
  ggplot(aes(x = DateTime, y = co2_umolL, color = as.factor(Depth_m)))+
  scale_color_discrete(name = "Depth (m)")+
  geom_point()+
  ggtitle("Site 50")
```

