---
title: "CTD Meta Processing"
author: "Abby Lewis"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(akima)
library(colorRamps)
library(rLakeAnalyzer)
library(readxl)
```

Pull in CTD data from EDI and plot changes resulting from drawdown in 2022, 2021 control

read data from EDI
```{r}
inUrl1  <- "https://pasta.lternet.edu/package/data/eml/edi/200/12/0a62d1946e8d9a511bc1404e69e59b8c" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 ctd_hist <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "Date",     
                    "Depth_m",     
                    "Temp_C",     
                    "DO_mgL",     
                    "DO_pSat",     
                    "Cond_uScm",     
                    "Spec_Cond_uScm",     
                    "Chla_ugL",     
                    "Turb_NTU",     
                    "pH",     
                    "ORP_mV",     
                    "PAR_umolm2s",     
                    "Desc_rate",     
                    "Flag_Temp",     
                    "Flag_DO",     
                    "Flag_Cond",     
                    "Flag_SpecCond",     
                    "Flag_Chla",     
                    "Flag_Turb",     
                    "Flag_pH",     
                    "Flag_ORP",     
                    "Flag_PAR",     
                    "Flag_DescRate"    ), check.names=TRUE)
               
unlink(infile1)
```

Read data from 2022
```{r}
# This reads all the files into the R environment
files = list.files("../csv_outputs/",pattern = ".*\\d+.*.csv") #Get all csv files
files <- files[!grepl("PAR",files)&!grepl("matlab",files)] #That do not include PAR or matlab
files <- files[grepl("bvr",files)] #That are from bvr
files <- files[substring(files,5,6)=="22"]
files <- files[files!="051722_bvr50_0002.csv"]

#This reads the first file in
ctd = read_csv(paste0("../csv_outputs/",files[1])) 
location <- sub("^[0-9]*_","",sub("\\.csv","",files[1]))
ctd = ctd%>%
    mutate(Reservoir = toupper(sub("[0-9]+.*","",location)),
           Site = as.numeric(sub("_.*","",sub("^[A-Z|a-z]*","",sub("_[a-z]+","",location)))))%>%
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')%>%
    select(-Salinity)

# Loop through and pull all the files in
for (i in 2:length(files)){
  new = read_csv(paste0("../csv_outputs/",files[i]))
  location <- sub("^[0-9]*_","",sub("\\.csv","",files[i]))
  new = new%>%
    mutate(Reservoir = toupper(sub("[0-9]+.*","",location)),
           Site = as.numeric(sub("_.*","",sub("^[A-Z|a-z]*","",sub("_[a-z]+","",location)))))%>%
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')%>%
    select(-Salinity)
  ctd = ctd %>%
    full_join(new)
}
write_csv(ctd, "../CTD_season_csvs/CTD_BVR_2022.csv")
```

Make heatmaps (using depth, not elevation)
```{r}
ctd <- read.csv("../CTD_season_csvs/CTD_BVR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"))%>%
    mutate(Site = ifelse(Site==1,40,Site))%>%
  full_join(ctd_hist%>%mutate(Date=as.Date(Date)))%>%
  filter(month(Date)>=5)

#Decrease dataset size by triming to 0.1m depth intervals
depths <- seq(0,11, by = .1)
newDepths <- depths
df.final<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final <- rbind(df.final,ctd_atThisDepth)
}

vars = c("Temp_C","Chla_ugL","Turb_NTU","Cond_uScm","Spec_Cond_uScm","DO_mgL","DO_pSat","pH","ORP_mV","PAR_umolm2s","Desc_rate")
Sites = c(50,40)
Years = c(2021,2022)
for(var in vars){
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  for(site in Sites){
    for(year in Years){
        bvr<- df.final%>%
          mutate(Year = year(Date),
                 Date = as.Date(Date))%>%
          filter(Site == site,
                 Year == year,
                 Reservoir == "BVR",
                 !is.na(get(var)))
        if(nrow(bvr)>0){
          bvr_interp <- interp2xyz(interp(bvr$Date,bvr$Depth_m,bvr[[var]],xo = seq(min(bvr$Date), max(bvr$Date), .1),yo = seq(min(bvr$Depth_m), max(bvr$Depth_m), by = .01), duplicate = "mean"),data.frame = T)
          interp = interp%>%
            full_join(bvr_interp%>%mutate(Site=site))
      }
    }
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  #Heatmap
  jpeg(paste0("../2022_BVR_drawdown_figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot(aes(x=x, y=y))+
    geom_raster(aes(fill = z))+
    scale_y_reverse(expand = c(0,0))+
    labs(x = "", y = "Depth (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(blue2green2red(100))}else{blue2green2red(100)}, na.value="gray", name = var)+
    geom_point(data = bvr, aes(x = Date, y = min(Depth_m)), shape = 25, fill = "black", color = "white", size  =2)+
    scale_x_date(expand = c(0,0))+
    theme(panel.border = element_rect(fill = NA))+
    facet_grid(rows= vars(Site),
               cols = vars(Year),
               scales = "free",
               space = "free"
               )
  print(p)
  dev.off()
}
```

Elevation instead of depth
```{r}
ctd <- read.csv("../CTD_season_csvs/CTD_BVR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"))%>%
    mutate(Site = ifelse(Site==1,40,Site))%>%
  full_join(ctd_hist%>%mutate(Date=as.Date(Date))%>% filter(Reservoir=="BVR"))%>%
  filter(month(Date)>=5,
         month(Date)<=8)

#Decrease dataset size by trimming to 0.1m depth intervals
depths <- seq(0,11, by = .1)
newDepths <- depths
df.final<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final <- rbind(df.final,ctd_atThisDepth)
}
df.final.raw = df.final

#Load YSI data from EDI
inUrl2  <- "https://pasta.lternet.edu/package/data/eml/edi/198/9/b3bd353312f9e37ca392e2a5315cc9da" 
infile2 <- tempfile()
try(download.file(inUrl2,infile2,method="curl"))
if (is.na(file.size(infile2))) download.file(inUrl2,infile2,method="auto")
 ysi <-read.csv(infile2,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "Temp_C",     
                    "DO_mgL",     
                    "DOSat",     
                    "Cond_uScm",     
                    "Sp_cond_uScm",     
                    "PAR_umolm2s",     
                    "ORP_mV",     
                    "pH",     
                    "Flag_DateTime",     
                    "Flag_Temp",     
                    "Flag_DO",     
                    "Flag_DOSat",     
                    "Flag_Cond",     
                    "Flag_Sp_Cond",     
                    "Flag_PAR",     
                    "Flag_ORP",     
                    "Flag_pH"    ), check.names=TRUE)
               
unlink(infile2)

#Format YSI data
ysi_formatted = ysi%>%
  filter(!is.na(DO_mgL),
         Site == 50)%>% #Only the deepest site
  mutate(Date = as.Date(DateTime))%>%
  select("Reservoir",
         "Site",
         "Date",
         "Depth_m",
         "DO_mgL",
         "DOSat",
         "pH")%>%
  #We are only using YSI to fill in gaps in CTD data. Select data for those gaps here
  filter((Date>=as.Date("2021-04-01")&Date<as.Date("2021-9-01")),
         )%>%
  mutate(DO_mgL = ifelse(Date<=as.Date("2021-07-01"),NA,DO_mgL),
         DO_pSat = ifelse(Date<=as.Date("2021-07-01"),NA,DOSat))%>%
  mutate(method = "ysi")%>%
  select(-DOSat)

ctd_depths = df.final%>%
  mutate(Date = as.Date(Date),
         Year = year(Date))%>%
  filter(Year %in% Years,
         Site %in% Sites,
         Reservoir == "BVR"
         )%>%
  group_by(Date,Site,Year)%>%
  summarize(WaterLevel = max(Depth_m))%>%
  group_by(Site)%>%
  mutate(max = max(WaterLevel))

# Combine CTD and YSI data
df.final = df.final.raw%>%
  group_by(Date, Site)%>%
  mutate(max = max(Depth_m),
         DO_mgL = ifelse(Date>as.Date("2021-07-01")&Date<as.Date("2021-12-01"),NA,DO_mgL))%>%
  full_join(ysi_formatted%>%rename(pH_ysi = pH, DO_mgL_ysi = DO_mgL, DO_pSat_ysi = DO_pSat))%>%
  mutate(pH=ifelse(is.na(pH),pH_ysi,pH),
         DO_mgL=ifelse(is.na(DO_mgL),DO_mgL_ysi,DO_mgL),
         DO_pSat=ifelse(is.na(DO_pSat),DO_pSat_ysi,DO_pSat))%>%
  mutate(Depth_m = max -Depth_m)

df.final%>%
  filter(method=="ysi")

#library(RCurl)
#sensor <- read.csv(text = getURL("https://raw.githubusercontent.com/FLARE-forecast/BVRE-data/bvre-platform-data/bvre-waterquality.csv"))

#sensor_depth = sensor%>%
#  mutate(DateTime = as.POSIXct(TIMESTAMP),
#         WaterLevel = Lvl_psi*0.70455)%>%
#  filter(year(DateTime)==2022,
#         WaterLevel>7.5)%>%
#  arrange(DateTime)%>%
#  filter(!lag(WaterLevel)-WaterLevel>0.2)%>%
#  mutate(Date = as.Date(DateTime))%>%
#  group_by(Date)%>%
#  summarize(WaterLevel = mean(WaterLevel))%>%
#  mutate(Year = year(Date),
#         Site = 50)

#sensor_depth = sensor_depth%>%
#  full_join(sensor_depth%>%mutate(Site=40,
#                                  WaterLevel = WaterLevel-5.5))

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"), Year = 2022)

vars = c("Temp_C","Chla_ugL","Turb_NTU","Cond_uScm","Spec_Cond_uScm","DO_mgL","DO_pSat","pH","ORP_mV","PAR_umolm2s","Desc_rate")
Sites = c(50,40)
Years = c(2021,2022)

ysi%>%
  filter(Depth_m==15)

df.final%>%
  filter(Date=="2021-05-31")

for(var in vars){
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  for(site in Sites){
    for(year in Years){
      bvr<- df.final%>%
        mutate(Year = year(Date),
               Date = as.Date(Date))%>%
        filter(Reservoir == "BVR",
               !is.na(get(var)),
               !is.na(Depth_m),
               Site %in% Sites,
               Year %in% Years)%>%
        group_by(Site)%>%
        mutate(max = max(Depth_m))
      bvr_site<- bvr%>%
        filter(Site == site,
               Year == year)
      if(nrow(bvr_site)>0){
        bvr_interp <- interp2xyz(interp(bvr_site$Date,bvr_site$Depth_m,bvr_site[[var]],xo = seq(min(bvr_site$Date), max(bvr_site$Date), .1),yo = seq(min(bvr_site$Depth_m), max(bvr_site$Depth_m), by = .01), duplicate = "mean"),data.frame = T)
        interp = interp%>%
          full_join(bvr_interp%>%mutate(Site=site))
      }
    }
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  bvr_maxes = bvr%>%
    group_by(Site)%>%
    summarize(max = unique(max))
  
  #sensor_depth_plot = sensor_depth%>%
  #  full_join(bvr_maxes)%>%
  #  filter(Date>= min(bvr$Date),
  #         Date<= max(bvr$Date),
  #         WaterLevel<=max)
  
  #Heatmap
  jpeg(paste0("../2022_BVR_drawdown_figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot(aes(x=x))+
    geom_raster(aes(fill = z, y=y))+
    geom_ribbon(data = ctd_depths, aes(x = Date, ymin= WaterLevel, ymax = max), fill = "white")+
    scale_y_continuous(expand = c(0,0))+
    labs(x = "", y = "Height above sediments (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(blue2green2red(100))}else{blue2green2red(100)}, na.value="white", name = var)+
    geom_point(data = bvr, aes(x = Date, y = max), shape = 25, fill = "black", color = "white", size  =2)+
    geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
    scale_x_date(expand = c(0,0))+
    theme_classic()+
    theme(panel.border = element_rect(fill = NA))+
    facet_grid(rows= vars(Site),
               cols = vars(Year),
               scales = "free",
               space = "free_y")
  print(p)
  dev.off()
}
```

Stratification statisitcs
```{r}
ctd <- read.csv("../CTD_season_csvs/CTD_BVR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"),
         Date = as.Date(Date))%>%
    mutate(Site = ifelse(Site==1,40,Site))

#ctd_01 = ctd%>%
#  full_join(ctd_hist%>%mutate(Date=as.Date(Date)))%>%
#  group_by(Date, Site, Reservoir)%>%
#  filter(Depth_m == Depth_m[which.min(abs(Depth_m-0.1))])
#
#write.csv(ctd_01,"CTD_surface.csv", row.names = F)

ctd_bvr_hist = ctd_hist%>%
  mutate(Date = as.Date(Date))%>%
  filter(Reservoir == "BVR",
         Site == 50,
         year(Date)==2021)

ctd = ctd%>%
  full_join(ctd_bvr_hist)%>%
  filter(month(Date)>=5)

#Decrease dataset size by trimming to 0.1m depth intervals
depths <- seq(0,11, by = .01)
newDepths <- depths
df.final<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final <- rbind(df.final,ctd_atThisDepth)
}

new_depths = df.final%>%
  group_by(Date, Site)%>%
  mutate(Depth_m = max(Depth_m)-Depth_m)

library(rLakeAnalyzer)
strat = df.final%>%
  group_by(Date,Site)%>%
  summarize(buoy_freq = max(buoyancy.freq(Temp_C,Depth_m)),
            thermo = thermo.depth(Temp_C,Depth_m),
            epi = meta.depths(Temp_C,Depth_m)[1],
            hypo = meta.depths(Temp_C,Depth_m)[2],
            tdo3 = Temp_C[which.min(Depth_m[DO_mgL<3])],
            t = Temp_C[which.min(Depth_m)])%>%
  mutate(Year = year(Date))
strat$Date_22 = strat$Date
year(strat$Date_22)=2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg("../2022_BVR_drawdown_figs/Buoyancy_freq.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = buoy_freq, color = as.factor(Year)))+
  geom_point()+
  ylab("Buoyancy frequency (sec^-2)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")
#+facet_wrap(~Year, scales = "free_x")
dev.off()

jpeg("../2022_BVR_drawdown_figs/Thermo_depth.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = thermo, color = as.factor(Year)))+
  geom_point()+
  geom_line()+
  ylab("Thermocline: depth from surface (m)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

jpeg("../2022_BVR_drawdown_figs/Epi_thickness.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = epi, color = as.factor(Year)))+
  geom_point()+
  geom_line()+
  ylab("Epilimnion thickness (m)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

oxy = df.final%>%
  filter(DO_mgL<3)%>%
  group_by(Date,Site)%>%
  summarize(tdo3 = Temp_C[which.min(Depth_m)],
            Depth_m = min(Depth_m))%>%
  mutate(Year = as.factor(year(Date)),
         Date_22 = Date)
year(oxy$Date_22)=2022

jpeg("../2022_BVR_drawdown_figs/TDO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = tdo3, color = Year))+
  geom_point()+
  geom_line()+
  ylab("Temperature at which DO > 3")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

jpeg("../2022_BVR_drawdown_figs/Depth_DO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = Depth_m, color = Year))+
  geom_point()+
  geom_line()+
  ylab("Depth at which DO > 3")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_y_reverse()+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

bathy = read.csv("../2022_BVR_drawdown_figs/Bathymetry_comb.csv")%>%
  filter(Reservoir == "BVR")

#For some reason schmidt doesn't run unless we filter to 1m
depths <- seq(0,11, by = 1)
newDepths <- depths
df.final.1m<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final.1m$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final.1m <- rbind(df.final.1m,ctd_atThisDepth)
}

ctd_depths = df.final.1m%>%
  mutate(Date = as.Date(Date))%>%
  filter(Site == 50)%>%
  group_by(Date)%>%
  summarize(WaterLevel = max(Depth_m))

flexible_bathy = ctd_depths%>%
  mutate(Reservoir = "BVR")%>%
  full_join(bathy)%>%
  group_by(Date)%>%
  mutate(Depth_m = Depth_m - (max(Depth_m)-unique(WaterLevel)) + 1)%>%
  filter(Depth_m>=0)

site50 = df.final%>%
  filter(Site == 50)

schmidts = c()
for(date in unique(site50$Date)){
  temps = site50%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  schmidts = c(schmidts, schmidt.stability(wtr = temps$Temp_C, depths = temps$Depth_m, bthA = baths$SA_m2, bthD = baths$Depth_m, sal = rep(0,length(temps$Temp_C))))
}

schmidt_df = data.frame(Date = unique(site50$Date), Schmidt = schmidts)%>%
  mutate(Year = year(Date))
schmidt_df$Date_22 = schmidt_df$Date
year(schmidt_df$Date_22)=2022

jpeg("../2022_BVR_drawdown_figs/Schmidt_stability.jpg", width = 6, height = 4, res = 300, units = "in")
schmidt_df%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Schmidt, color = Year))+
  geom_point()+
  geom_line()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Schmidt stability (J/m^2)")+
  theme_bw()+
  xlab("Date")
dev.off()

jpeg("../2022_BVR_drawdown_figs/Schmidt_stability_blank.jpg", width = 6, height = 4, res = 300, units = "in")
schmidt_df%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Schmidt, color = Year))+
  geom_point(alpha = 0)+
  geom_line(alpha = 0)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Schmidt stability (J/m^2)")+
  theme_bw()+
  xlab("Date")
dev.off()
```


Determine interflow depth
```{r}
ysi = read_excel("2022_YSI_PAR_Profiles.xlsx")%>%
  mutate(Site = as.numeric(Site))

inUrl2  <- "https://pasta.lternet.edu/package/data/eml/edi/198/10/b3bd353312f9e37ca392e2a5315cc9da" 
infile2 <- tempfile()
try(download.file(inUrl2,infile2,method="curl"))
if (is.na(file.size(infile2))) download.file(inUrl2,infile2,method="auto")

                   
 dt2 <-read.csv(infile2,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "Temp_C",     
                    "DO_mgL",     
                    "DOSat",     
                    "Cond_uScm",     
                    "Sp_cond_uScm",     
                    "PAR_umolm2s",     
                    "ORP_mV",     
                    "pH",     
                    "Flag_DateTime",     
                    "Flag_Temp",     
                    "Flag_DO",     
                    "Flag_DOSat",     
                    "Flag_Cond",     
                    "Flag_Sp_Cond",     
                    "Flag_PAR",     
                    "Flag_ORP",     
                    "Flag_pH"    ), check.names=TRUE)%>%
   mutate(DateTime = as.POSIXct(DateTime))
               
unlink(infile2)

ysi_filt = ysi%>%
  full_join(dt2)%>%
  filter(Reservoir == "FCR", 
         Site == "100")%>%
  mutate(Year = as.factor(year(DateTime)),
         Date_22 = DateTime)%>%
  filter(month(DateTime)<=8,
         month(DateTime)>=4)
year(ysi_filt$Date_22)<- 2022

ctd <- read.csv("../CTD_season_csvs/CTD_FCR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"),
         Date = as.Date(Date))

ctd%>%
  filter(Date %in% as.Date(ysi_filt$DateTime))

depths = c()
dates = c()
for(date in as.Date(ysi_filt$DateTime)){
  new = ctd%>%
    filter(Date == date,
           !is.na(Temp_C))
  if(nrow(new)>0){
    dates = c(dates, date)
  }
  temp = ysi_filt$Temp_C[as.Date(ysi_filt$DateTime)==date]
  depths = c(depths,new$Depth_m[which.min(abs(new$Temp_C - temp))])
}
inflow_depth = data.frame(Date = as.Date(dates, origin = "1970-01-01"), Depth_m = depths)

```


```{r}
###
#LOAD DATA
###

ctd <- read.csv("../CTD_season_csvs/CTD_FCR_2022.csv")%>% #load CTD data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"),
         Date = as.Date(Date))

#Load bathymetry
bathy = read.csv("../2022_BVR_drawdown_figs/Bathymetry_comb.csv")%>%
  filter(Reservoir == "FCR")



###
# FORMAT DATA
###

#For some reason schmidt doesn't run unless we filter to 1m intervals. The whole mess of code below is just to do this
depths <- seq(0,10, by = 1) #Set up the depths that we want
newDepths <- depths
df.final.1m<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final.1m$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final.1m <- rbind(df.final.1m,ctd_atThisDepth)
}



###
# CALCULATE SCHMIDT
###

#Once you have a filtered CTD dataset and bathymetry loaded, calculating Schmidt Stability is easy!
schmidt = df.final.1m%>%
  filter(Site == 50)%>% #Make sure we are only looking at Site 50 data
  group_by(Date)%>%
  summarize(schmidt = schmidt.stability(wtr = Temp_C, 
                                        depths = Depth_m,
                                        bthA = bathy$SA_m2, 
                                        bthD = bathy$Depth_m,
                                        sal = rep(0,length(Temp_C))#Salinity is approximately 0 (freshwater)
                                        )
            )


###
# PLOT RESULTS
###
schmidt%>%
  ggplot(aes(x = Date, y = schmidt))+
  geom_point()

```

Light attenuation/light extinction
```{r}
#Using the equation here
#https://www.esf.edu/efb/schulz/Limnology/Light.html

ctd <- read.csv("../CTD_season_csvs/CTD_BVR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"))%>%
    mutate(Site = ifelse(Site==1,40,Site))%>%
  full_join(ctd_hist%>%
              mutate(Date=as.Date(Date))%>%
              filter(Reservoir=="BVR"))%>%
  filter(month(Date)>=5,
         month(Date)<10,
         Site == 50)

atten_k = ctd%>%
  filter(!is.na(PAR_umolm2s))%>%
  group_by(Date)%>%
  filter(sum(Depth_m<0)>0)%>%
  mutate(I0 = mean(PAR_umolm2s[Depth_m<0], na.rm = T))%>%
  filter(Depth_m>0)%>%
  summarize(I0 = unique(I0),
            k = coef(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m)),
            r2 = summary(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m))$r.squared,
            Zeu = min(Depth_m[PAR_umolm2s<I0/100]),
            Zeu_0.1 = min(Depth_m[PAR_umolm2s<I0/1000]))%>%
  filter(r2>0.9)

write.csv(atten_k,"attenuation_calc.csv",row.names = F)

atten_k$Date_22<-atten_k$Date
year(atten_k$Date_22)=2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg("../2022_BVR_drawdown_figs/Light attenuation.jpg", width = 6, height = 4, res = 300, units = "in")
atten_k%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year%in%c(2022,2021))%>%
  ggplot(aes(x = Date_22, y = k, color = Year))+
  geom_line()+
  geom_point()+
  geom_vline(data=lines,aes(xintercept = as.POSIXct(Dates), lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Light attenuation coefficient")+
  theme_bw()+
  xlab("")
dev.off()

ctd%>%
  filter(Date=="2022-05-09 08:06:53	")

summary(ctd$PAR_umolm2s)

#strat is defined in a code chunk above
jpeg("../2022_BVR_drawdown_figs/Zeu_thermo.jpg", width = 6, height = 4, res = 300, units = "in")
strat%>%
  filter(Site==50)%>%
  select(-Date_22)%>%
  mutate(Date = as.Date(Date),
         Year = as.factor(year(Date)))%>%
  full_join(atten_k%>%
              mutate(Date = as.Date(Date)))%>%
  filter(year(Date)%in%c(2021,2022))%>%
  ggplot(aes(x = Date_22, y = Zeu/thermo, color = Year))+
  geom_line()+
  ylab("Euphotic zone:mixed layer depth")+
  xlab("")+
  geom_hline(yintercept = 1)+
  theme_bw()
dev.off()
```

