---
title: "Combine CTD files"
author: "Adrienne"
date: "2023-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!"pacman" %in% installed.packages()) install.packages("pacman")
pacman::p_load("lubridate","tidyverse")

start_date=as.POSIXct("2023-01-01 00:00:01")
end_date=as.POSIXct("2023-12-31 23:59:00")
current_year=23

```

```{r Combine new SN8188 csv}

files = list.files("../csv_outputs/",pattern = paste0(current_year,"_")) #Get all csv files

#This reads the first file in
ctd = read_csv(paste0("../csv_outputs/",files[1])) 
location <- sub("^[0-9]*_","",sub("\\.csv","",files[1]))
ctd= ctd%>%
    mutate(Reservoir = toupper(sub("[[:digit:]]_.*", "",sub("[[:digit:]]", "",location))),
           Site = as.numeric(sub("_.*","",sub("^[A-Z|a-z]*","",location))),
           SN = str_extract(location, "\\d{4}"))%>% #extracts 4 digit serial number
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')


# Loop through and pull all the files in
for (i in 2:length(files)){
  new = read_csv(paste0("../csv_outputs/",files[i]))
  location <- sub("^[0-9]*_","",sub("\\.csv","",files[i]))
  new = new%>%
    mutate(Reservoir = toupper(sub("[[:digit:]]_.*", "",sub("[[:digit:]]", "",location))),
           Site = as.numeric(sub("_.*","",sub("^[A-Z|a-z]*","",location))),
           SN = str_extract(location, "\\d{4}"))%>% #extracts 4 
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')
    
  ctd = ctd %>%
    full_join(new)
}

#filter out blank rows
new=ctd%>%
  #filter(Date!="")%>%
  filter(Depth_m>0)%>%
  add_column(CTD_check = NA)%>%#create the CTD_check column
  #sets up criteria for the CTD_check column either "good","bad" or "NA"(if no data)
  mutate(
    CTD_check=ifelse(Temp_C<25& Cond_uScm<Spec_Cond_uScm & !is.na(Spec_Cond_uScm), "good",CTD_check),
    CTD_check=ifelse(Temp_C<25& Cond_uScm>Spec_Cond_uScm & !is.na(Spec_Cond_uScm), "bad",CTD_check),
    CTD_check=ifelse(Temp_C>25& Cond_uScm>Spec_Cond_uScm & !is.na(Spec_Cond_uScm), "good",CTD_check),
    CTD_check=ifelse(Temp_C>25& Cond_uScm<Spec_Cond_uScm & !is.na(Spec_Cond_uScm), "bad",CTD_check),
    CTD_check=ifelse(is.na(Spec_Cond_uScm), "good",CTD_check),
    CTD_check=ifelse(Cond_uScm==0, "bad", CTD_check))%>%
  #the next part switches the column if labeled "bad" in CTD_check 
  transform(., Spec_Cond_uScm = ifelse(CTD_check == 'bad' & !is.na(Spec_Cond_uScm), Cond_uScm, Spec_Cond_uScm), 
            Cond_uScm = ifelse(CTD_check == 'bad' & !is.na(Spec_Cond_uScm), Spec_Cond_uScm, Cond_uScm))%>%
  select(-CTD_check)%>%
  mutate(Cond_uScm=ifelse(Cond_uScm<0 & !is.na(Cond_uScm), NA, Cond_uScm),
         Spec_Cond_uScm=ifelse(Spec_Cond_uScm<0 & !is.na(Spec_Cond_uScm), NA, Spec_Cond_uScm))%>%
  filter(Date>as.POSIXct(start_date) & Date<as.POSIXct(end_date))%>%
  select(SN,Reservoir,Site,Date,everything(),Flag)

write.csv(new, "../CTD_season_csvs/CTD_nonmatlab_ready_2023.csv", row.names=FALSE)



```

