---
title: "Light attenuation"
author: "Abby Lewis"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

```{r}
#Using the equation here
#https://www.esf.edu/efb/schulz/Limnology/Light.html

ctd <- read.csv("../CTD_EDI/CTD_2013_2022.csv")%>% #load saved data
  filter(Reservoir=="FCR")%>%
  filter(Site == 50)%>%
  mutate(Date = as.POSIXct(DateTime, format = "%Y-%m-%d %H:%M:%S"))

atten_k = ctd%>%
  filter(!is.na(PAR_umolm2s))%>%
  group_by(Date)%>%
  filter(sum(Depth_m<0)>0)%>% #Filter so there is at least one measurement out of the water
  mutate(I0 = mean(PAR_umolm2s[Depth_m<0], na.rm = T))%>% #I0 is the mean of surface measures
  filter(Depth_m>0)%>%
  summarize(I0 = unique(I0),
            k = coef(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m)), #From light attenuation eq.
            r2 = summary(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m))$r.squared, #R2
            Zeu = min(Depth_m[PAR_umolm2s<I0/100]), #Euphotic zone = 1% of surface light
            Zeu_0.1 = min(Depth_m[PAR_umolm2s<I0/1000]))%>% #Or 0.1% of surface light
  filter(r2>0.9)

write.csv(atten_k,"attenuation_calc_fcr.csv",row.names = F)

#Plot trends at FCR

atten_k%>%
  mutate(Year = as.factor(year(Date)))%>%
  ggplot(aes(x = Date, y = Zeu, color = Year))+
  geom_line()+
  geom_point()+
  ylab("Euphotic zone depth (m)")+
  theme_bw()+
  xlab("")+
  facet_wrap(~Year, scales= "free_x")

atten_k%>%
  mutate(Year = as.factor(year(Date)))%>%
  ggplot(aes(x = Date, y = k, color = Year))+
  geom_line()+
  geom_point()+
  ylab("Light attenuation")+
  theme_bw()+
  xlab("")+
  facet_wrap(~Year, scales= "free_x")
```

