---
title: "Robotics CTD casts"
author: "Adrienne"
date: "2023-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, lubridate, akima, colorRamps, googlesheets4)

```

```{r Read in CTD files}

# This reads all the files into the R environment
files = list.files("../csv_outputs/UF_Robotics_casts_S8188/",pattern = ".csv") #Get all csv files

#This reads the first file in
ctd = read_csv(paste0("../csv_outputs/UF_Robotics_casts_S8188/",files[1])) 
location <- sub("^[0-9]*_","",sub("\\.csv","",files[1]))
ctd = ctd%>%
    mutate(Reservoir = toupper(sub("XX_.*", "", location)),
           Cast_Number = as.numeric(sub("_S8188*","",sub("^[A-Z|a-z]*","",location))))%>%
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')

# Loop through and pull all the files in
for (i in 2:length(files)){
  new = read_csv(paste0("../csv_outputs/UF_Robotics_casts_S8188/",files[i]))
  location <- sub("^[0-9]*_","",sub("\\.csv","",files[i]))
  new = new%>%
    mutate(Reservoir = toupper(sub("XX_.*", "", location)),
           Cast_Number = as.numeric(sub("_S8188*","",sub("^[A-Z|a-z]*","",location))))%>%
    rename(PAR_umolm2s = PAR,
           Desc_rate = 'Descent Rate (m/s)')
    
  ctd = ctd %>%
    full_join(new)
}
write_csv(ctd, "../csv_outputs/UF_Robotics_casts_S8188/CTD_UF_FCR_20230627.csv")

```

```{r read in compiled Robot casts}
ctd<- read_csv("../csv_outputs/UF_Robotics_casts_S8188/CTD_UF_FCR_20230627.csv")

```

```{r read in CTD coordinates}

GPS_cords <- read_sheet('https://docs.google.com/spreadsheets/d/1VcCdhW1afPSDflB3ynBE5YRNPVzy2635XrwdkLQfSCs/edit#gid=0')

cords <- GPS_cords%>%
  rename("Cast_Number" = "CTD_cast")%>%
  select(Cast_Number, Longitude, Latitude)

```

```{r merge data frames to get coordinates}
ctd_2<-merge(ctd,cords, by="Cast_Number")

# Take out values when CTD out of the water
ctd_2 <- ctd_2%>% filter(Depth_m>0)%>%
  mutate(TDS_mgL=Spec_Cond_uScm*0.64)

```

```{r Table with Max and Min for each site}

# average to 0.1 

ctd_avg<-ctd_2 %>%
  mutate(Depth_m=round(Depth_m, digits = 1))%>%
  group_by(Depth_m, Cast_Number, Longitude, Latitude)%>%
  summarise(across(c(Temp_C:Salinity,TDS_mgL), mean))%>%
  ungroup()

# Max and Min for each site
    
surface<-ctd_avg %>%
  filter(Depth_m==0.1)

a<-ctd_avg %>% group_by(Cast_Number) %>% top_n(1, Depth_m)

ad<-ctd_avg %>% group_by(Cast_Number) %>% top_n(-1, Depth_m)

# Max DO for the casts
ab<-ctd_avg %>% group_by(Cast_Number) %>% top_n(1, DO_mgL)

# Min Temp for the casts
ac<-ctd_avg %>% group_by(Cast_Number) %>% top_n(-1, Temp_C)

# Max Chla for the casts
ae<-ctd_avg %>% group_by(Cast_Number) %>% top_n(1, Chla_ugL)
 
nax <- ctd_avg%>%
  group_by(Cast_Number)%>%
  

ctd_avg[ctd_avg[, .I[Depth_m == max(Depth_m)], by=Cast_Number]$V1]

```

