---
title: "ICE Inspection"
author: "Austin Delany"
date: "2025-01-17"
output: html_document
---

```{r setup, include=FALSE}

## FOCUSING ON INSPECTION OF ICE TRANSITION DATES ##
## daily binary product is interpolated from ice transition dates, so transitions should be main focus ##

library(tidyverse)
library(readr)
library(plotly)

## use function to read in data 
source('https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Scripts/L1_functions/ice_transition_binary_create.R')

current_files <- c("https://raw.githubusercontent.com/FLARE-forecast/BVRE-data/bvre-platform-data-qaqc/bvre-waterquality_L1.csv",
                   "https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/fcre-catwalk-data-qaqc/fcre-waterquality_L1.csv")

historic_wq_files <- c('https://pasta.lternet.edu/package/data/eml/edi/725/4/9adadd2a7c2319e54227ab31a161ea12',
                       'https://pasta.lternet.edu/package/data/eml/edi/271/8/fbb8c7a0230f4587f1c6e11417fe9dce')

historic_ice_files <- c("https://pasta.lternet.edu/package/data/eml/edi/456/5/ebfaad16975326a7b874a21beb50c151")

ice_maintenance_log <- c('https://docs.google.com/spreadsheets/d/1viYhCGs3UgstzHEWdmP2Ig6uxyNM3ZC_uisG_R0QNpI/edit?gid=0#gid=0')


bvr_ice_data <- ice_transition_binary_create(current_file = current_files[1],
                                            historic_wq_file = historic_wq_files[1],
                                            historic_file = historic_ice_files,
                                            ice_site = 'BVR',
                                            maint_log = NULL)

fcr_ice_data <- ice_transition_binary_create(current_file = current_files[2],
                                            historic_wq_file = historic_wq_files[2],
                                            historic_file = historic_ice_files,
                                            ice_site = "FCR",
                                            maint_log = ice_maintenance_log)


### use L1 file and historic file in the future ##
```


```{r function, include=FALSE}
#FUNCTIONS TO USE

profile_plot_winter<-function(DATA, Varibles, use_year, plot_title){
     next_year <- as.numeric(use_year) + 1
     
     DATA$date <- as.Date(DATA$DateTime)
     
  winter_data <- DATA%>%
  filter(date >= as.Date(paste(as.numeric(use_year), 12, 15, sep = "-")), date <= as.Date(paste(next_year, 03, 15, sep = "-"))) |> 
  select(DateTime, Varibles)%>%
    pivot_longer(!c(DateTime), names_to = "sensor", values_to = "obs")%>%
  separate_wider_delim(sensor, "_", names = c("sensor", "unit", "depth"))%>%
    drop_na()%>%
    #mutate(DateTime = as.Date(DateTime)) |> 
  mutate(depth=ifelse(depth=="surface", 0.1, depth))%>%
    mutate(depth=as.numeric(depth))
    
  fig <- ggplot(winter_data, aes(DateTime,obs, col=as.factor(depth)))+
  geom_line()+
    #scale_x_datetime(date_breaks = "5 day", date_minor_breaks = "1 day")+
    theme_bw() +
    labs(title= paste0(plot_title,' ', use_year))

    ggplotly(fig)
    
    
    #facet_wrap( ~ year, ncol = 1, scales = "free_x")
  
}

## MAKE PLOT TO INVESTIGATE INDIVIDUAL ICE-ON EVENTS TO BE USED LATER IN THE SCRIPT
profile_plot_winter_events <-function(DATA, Varibles, interest_date, plot_title){
     #next_year <- as.numeric(use_year) + 1
  
  winter_data <- DATA%>%
    mutate(date = as.Date(DateTime)) |> 
    filter(date <= (as.Date(interest_date) + lubridate::days(7)), 
           date >= as.Date(interest_date) - lubridate::days(3)) |> 
  # filter(date >= as.Date(paste(use_year, 12, 15, sep = "-")), date <= as.Date(paste(next_year, 03, 15, sep = "-"))) |> 
  select(DateTime, Varibles)%>%
    pivot_longer(!c(DateTime), names_to = "sensor", values_to = "obs")%>%
  separate_wider_delim(sensor, "_", names = c("sensor", "unit", "depth"))%>%
    drop_na()%>%
    #mutate(DateTime = as.Date(DateTime)) |> 
  mutate(depth=ifelse(depth=="surface", 0.1, depth))%>%
    mutate(depth=as.numeric(depth))
    
  fig <- ggplot(winter_data, aes(DateTime,obs, col=as.factor(depth)))+
  geom_line()+
    #scale_x_datetime(date_breaks = "5 day", date_minor_breaks = "1 day")+
    theme_bw() +
    labs(title= paste0(plot_title,' ', interest_date))

    ggplotly(fig)
    
    
    #facet_wrap( ~ year, ncol = 1, scales = "free_x")
  
}
```


## FCR Plots

```{r, include = FALSE}
# Read in FCR, Met, and BVR data
fcr_current_catwalk <- read_csv('https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/refs/heads/fcre-catwalk-data-qaqc/fcre-waterquality_L1.csv')
fcr_historic_catwalk <- read_csv('https://pasta.lternet.edu/package/data/eml/edi/271/8/fbb8c7a0230f4587f1c6e11417fe9dce')

FCR_met<-read_csv("https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/fcre-metstation-data-qaqc/FCRmet_L1.csv")

FCR_Catwalk_EDI_2018_2024 <- dplyr::bind_rows(fcr_current_catwalk, fcr_historic_catwalk)
```


```{r, include=FALSE}
# CREATE WINTER PROFILES (filter data for only dates between Dec 15 - March 15)
FCR_Catwalk_EDI_2018_2024$year <- format(FCR_Catwalk_EDI_2018_2024$DateTime, "%Y")
FCR_Catwalk_EDI_2018_2024$month <- lubridate::month(FCR_Catwalk_EDI_2018_2024$DateTime)
FCR_Catwalk_EDI_2018_2024$day <- lubridate::day(FCR_Catwalk_EDI_2018_2024$DateTime)

fcr_catwalk_winter <- FCR_Catwalk_EDI_2018_2024 |> filter(month %in% c(12,1,2,3))

## COME BACK TO THIS TO FIGURE OUT HOW TO GET 12/15 - 3/15 FOR EACH YEAR

# FCR_Catwalk_EDI_2018_2024$year_ahead<- lubridate::year(FCR_Catwalk_EDI_2018_2024$DateTime + lubridate::years(1))
# 
# # fcr_catwalk_winter <- FCR_Catwalk_EDI_2018_2024 %>% filter(date >= as.Date(paste(year, 12, 15, sep = "-")), date <= as.Date(paste(year_ahead, 03, 15, sep = "-")))
```

## PLOT FCR WINTER TEMPERATURES 
```{r, echo=FALSE}
interest_years <- sort(unique(fcr_catwalk_winter$year), decreasing = FALSE)[1:7]

# profile_plot_winter(DATA=fcr_catwalk_winter,
#            Varibles = starts_with("Thermis"))

# outputs <- lapply(interest_years, 
#                   profile_plot_winter, 
#                   DATA = fcr_catwalk_winter,
#                   Varibles = starts_with("Thermis"))

#output <- unlist(outputs, recursive = F)

plots <- interest_years %>% 
  purrr::map(~profile_plot_winter(DATA = fcr_catwalk_winter,  
                                  Varibles = starts_with("Thermis"), 
                                  use_year = .x,
                                  plot_title = 'FCR Temp'))
plots
```



## PLOT FCR DO TEMPERATURES 
```{r, echo=FALSE}
interest_years <- sort(unique(fcr_catwalk_winter$year), decreasing = FALSE)[1:7]


plots <- interest_years %>% 
  purrr::map(~profile_plot_winter(DATA = fcr_catwalk_winter,  
                                  Varibles = c("RDOsat_percent_5", "RDOsat_percent_9", "EXODOsat_percent_1"), 
                                  use_year = .x,
                                  plot_title = 'FCR DO'))
plots
```

## IDENTIFY ICE TRANSITION DATES
```{r, include=TRUE}
## print transition dates for publishing year and December of previous year (capture possible ice duration between years)

fcre_transition <- fcr_ice_data |> 
  filter(DateTime > as.Date('2018-12-01')) |> 
  select(DateTime, IceOn, Method) |> 
  arrange(DateTime)

print(fcre_transition)

```

```{r, echo=FALSE}

fcr_ice_on_dates <- fcre_transition |> 
  filter(IceOn == 1) |> 
  mutate(Date = as.Date(DateTime)) |> 
  distinct(Date) |> 
  pull(Date)

plots <- fcr_ice_on_dates %>% 
  purrr::map(~profile_plot_winter_events(DATA = fcr_catwalk_winter,  
                                  Varibles = starts_with("Thermis"), 
                                  interest_date = .x,
                                  plot_title = 'FCR Temp for ice on: '))
plots
```


```{r, echo=FALSE}

plots <- fcr_ice_on_dates %>% 
  purrr::map(~profile_plot_winter_events(DATA = fcr_catwalk_winter,  
                                  Varibles = c("RDOsat_percent_5", "RDOsat_percent_9", "EXODOsat_percent_1"), 
                                  interest_date = .x,
                                  plot_title = 'FCR Temp for ice on: '))
plots
```





## BVR ICE

```{r, include = FALSE}
# Read in FCR, Met, and BVR data
bvre_current_catwalk <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/BVRE-data/bvre-platform-data-qaqc/bvre-waterquality_L1.csv")
bvre_historic_catwalk <- read_csv('https://pasta.lternet.edu/package/data/eml/edi/725/4/9adadd2a7c2319e54227ab31a161ea12')

BVR_Catwalk_EDI_2020_2024 <- dplyr::bind_rows(bvre_current_catwalk, bvre_historic_catwalk)
```


```{r, include=FALSE}
# CREATE WINTER PROFILES (filter data for only dates between Dec 15 - March 15)
BVR_Catwalk_EDI_2020_2024$year <- format(BVR_Catwalk_EDI_2020_2024$DateTime, "%Y")
BVR_Catwalk_EDI_2020_2024$month <- lubridate::month(BVR_Catwalk_EDI_2020_2024$DateTime)
BVR_Catwalk_EDI_2020_2024$day <- lubridate::day(BVR_Catwalk_EDI_2020_2024$DateTime)

bvr_catwalk_winter <- BVR_Catwalk_EDI_2020_2024 |> filter(month %in% c(12,1,2,3))

## COME BACK TO THIS TO FIGURE OUT HOW TO GET 12/15 - 3/15 FOR EACH YEAR

# FCR_Catwalk_EDI_2018_2024$year_ahead<- lubridate::year(FCR_Catwalk_EDI_2018_2024$DateTime + lubridate::years(1))
# 
# # fcr_catwalk_winter <- FCR_Catwalk_EDI_2018_2024 %>% filter(date >= as.Date(paste(year, 12, 15, sep = "-")), date <= as.Date(paste(year_ahead, 03, 15, sep = "-")))
```

## PLOT BVR WINTER TEMPERATURES 
```{r, echo=FALSE}
interest_years <- sort(unique(bvr_catwalk_winter$year), decreasing = FALSE)[1:5]

# profile_plot_winter(DATA=fcr_catwalk_winter,
#            Varibles = starts_with("Thermis"))

# outputs <- lapply(interest_years, 
#                   profile_plot_winter, 
#                   DATA = fcr_catwalk_winter,
#                   Varibles = starts_with("Thermis"))

#output <- unlist(outputs, recursive = F)

plots <- interest_years %>% 
  purrr::map(~profile_plot_winter(DATA = bvr_catwalk_winter,  
                                  Varibles = starts_with("Thermis"), 
                                  use_year = .x,
                                  plot_title = 'BVR Temp'))
plots
```



## PLOT BVR DO PROFILES 
```{r, echo=FALSE}
interest_years <- c(sort(unique(bvr_catwalk_winter$year), decreasing = FALSE))[1:5]


plots <- interest_years %>% 
  purrr::map(~profile_plot_winter(DATA = bvr_catwalk_winter,  
                                  Varibles = c("RDOsat_percent_6", "RDOsat_percent_13", "EXODOsat_percent_1.5"), 
                                  use_year = .x,
                                  plot_title = 'BVR DO'))
plots
```

## IDENTIFY ICE TRANSITION DATES
```{r, include=TRUE}
## print transition dates for publishing year and December of previous year (capture possible ice duration between years)

bvr_transition <- bvr_ice_data |> 
  filter(Date > as.Date('2020-12-01')) |> 
  select(Date, IceOn, Method) |> 
  arrange(Date)

print(bvr_transition)

```

```{r, echo=FALSE}

bvr_ice_on_dates <- bvr_transition |> 
  filter(IceOn == 1) |> 
  mutate(Date = as.Date(Date)) |> 
  pull(Date)

plots <- bvr_ice_on_dates %>% 
  purrr::map(~profile_plot_winter_events(DATA = bvr_catwalk_winter,  
                                  Varibles = starts_with("Thermis"), 
                                  interest_date = .x,
                                  plot_title = 'BVR Temp for ice on: '))
plots
```
