---
author: "Heather Wander"
date: "2023-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Add the names of the packages 
pacman::p_load(tidyverse, lubridate, scales, viridis)
```


```{r read in current + historic combined file}

new_chem <- read.csv("./Data/DataNotYetUpdloadedToEDI/NutrientData/chem_L1.csv")

old_chem <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/199/11/509f39850b6f95628d10889d66885b76", col_types = cols())

all_chem <- bind_rows(new_chem, old_chem)

```

```{r 2023 diagnostic plots}
#date format
new_chem$DateTime <- as.Date(new_chem$DateTime, "%Y-%m-%d %H:%M:%S")

#select columns for plotting
new_chem <- new_chem [,(names(new_chem) %in% c("Reservoir","Site","DateTime",
  "Depth_m","Rep","TP_ugL","TN_ugL","NH4_ugL","SRP_ugL","NO3NO2_ugL","DOC_mgL"))]

  #### Chemistry diagnostic plots ####
chemistry_long <- new_chem %>% 
  gather(metric, value, TP_ugL:DOC_mgL) %>% 
  mutate(month = strftime(DateTime, "%b"))

chemistry_long$value <- as.numeric(chemistry_long$value)


# Plot range of values per constituent for each reservoir; 
#mean value per sampling day indicated with large black dot
ggplot(subset(chemistry_long, Site == 50), aes(x = DateTime, y = value, col=Reservoir)) +
  geom_point(size=1) +
  stat_summary(fun.y="mean", geom="point",pch=21,  size=3, fill='black') +
  facet_grid(metric ~ Reservoir, scales= 'free_y') +
  scale_x_date(labels = date_format("%d %b")) +
  scale_y_continuous("Concentration at site 50") +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='none')
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/FCR_BVR_CCR_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

# FCR deep hole data time series
ggplot(subset(chemistry_long, Reservoir=='FCR' & Site=="50"), aes(x = DateTime, y = value, col=as.factor(Depth_m))) +
  geom_point(cex=2) + theme_bw()+
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_breaks="1 month", date_labels = "%d %b") +
  scale_y_continuous("Concentration at site 50") +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size=6),
        axis.text.y = element_text(size=6),
        legend.key.size = unit(0.5, 'lines'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=6)) +
  scale_color_manual("FCR_Depth (m)", values = viridis(10))
  #geom_vline(xintercept=as.numeric(as.Date(c("2021-06-11", "2021-07-12", "2021-07-26", "2022-03-22")))) +
  #geom_vline(xintercept=as.numeric(as.Date(c("2021-06-26", "2021-07-14","2021-12-06", "2022-03-24"))), linetype="dotted")
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/FCR_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

# FCR other sites nutrient data time series
ggplot(subset(chemistry_long, Reservoir=='FCR' & Site!="50"), aes(x = DateTime, y = value, col=as.factor(Site))) +
  geom_point(cex=2) + theme_bw() +
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_breaks="1 month", date_labels = "%d %b") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size=6),
        axis.text.y = element_text(size=6),
        legend.key.size = unit(0.5, 'lines'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=6)) + 
  scale_color_manual("FCR_Site", values = rainbow(10)) 
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/FCR_sites_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

# BVR deep hole data time series
ggplot(subset(chemistry_long, Reservoir=='BVR' & Site=="50"), aes(x = DateTime, y = value, col=as.factor(Depth_m))) +
  geom_point(cex=2) + theme_bw() +
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_breaks="1 month", date_labels = "%d %b") +
  scale_y_continuous("Concentration at site 50") +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size=6),
        axis.text.y = element_text(size=6),
        legend.key.size = unit(0.5, 'lines'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=6)) + 
  scale_color_manual("BVR_Depth (m)", values = plasma(10)) 
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/BVR_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

 #BVR other sites nutrient time series #no 2021 inflow samples so no figure :)
ggplot(subset(chemistry_long, Reservoir=='BVR' & Site!="50"), aes(x = DateTime, y = value, col=as.factor(Site))) +
  geom_point(cex=2) + theme_bw() +
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_labels = "%d %b") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 0, hjust=0.5)) + 
  scale_color_manual("BVR_Site", values = plasma(8)) 
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/BVR_sites_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

# CCR site 50 nutrient time series
#jpeg("./Figures/2021/CCR_50_all_nutrients_summer2021.jpg", width = 6, height = 5, units = "in",res = 300)
ggplot(subset(chemistry_long, Reservoir=='CCR' & Site=="50"), aes(x = DateTime, y = value, col=as.factor(Depth_m))) +
  geom_point(cex=2) + theme_bw() +
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_breaks="1 month", date_labels = "%d %b") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size=6),
        axis.text.y = element_text(size=6),
        legend.key.size = unit(0.5, 'lines'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=6)) + 
  scale_color_manual("CCR_Depth (m)", values = plasma(7)) 
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/CCR_50_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r 2023 diagnostic plots}

# CCR other sites nutrient time series
p1 <- ggplot(subset(chemistry_long, Reservoir=='CCR' & Site!="50"), aes(x = DateTime, y = value, col=as.factor(Site))) +
  geom_point(cex=2) + theme_bw() +
  facet_grid(metric ~ ., scales='free') +
  scale_x_date("Date", date_breaks="1 month", date_labels = "%d %b") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size=6),
        axis.text.y = element_text(size=6),
        legend.key.size = unit(0.5, 'lines'),
        legend.text = element_text(size=5),
        legend.title = element_text(size=6)) + 
  scale_color_manual("CCR_Site", values = plasma(6)) 
ggsave("./Data/DataNotYetUploadedToEDI/NutrientData/Figures/2023/CCR_sites_all_nutrients_summer2023.jpg", width=4, height=4)

```

```{r add additional columns to all chem df}
#add column for year
all_chem$year <- year(all_chem$DateTime)

#### YSI diagnostic plots #### 
all_chem_long <- all_chem %>%
  gather(metric, value, TP_ugL:DOC_mgL) %>% 
  mutate(month = strftime(DateTime, "%b"))

#value as numeric
all_chem_long$value<- as.numeric(all_chem_long$value)
all_chem_long$Depth_m<- as.numeric(all_chem_long$Depth_m)

```

```{r all data plots}

# Plot all values
ggplot(all_chem_long, aes(x = DateTime, y = value, col=Reservoir)) +
  geom_point(size=1) +
  stat_summary(fun.y="mean", geom="point",pch=21,  size=3, fill='black') +
  facet_grid(metric ~ Reservoir, scales= 'free_y') +
  scale_x_datetime("Date", date_breaks="2 months", date_labels = "%b %Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='none')
```

```{r all data plots}

# Deep hole time series for each reservoir
ggplot(subset(all_chem_long, Site=="50" & Reservoir=="BVR"), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Reservoir, scales='free') +
  scale_x_datetime("Date", date_breaks="1 month", date_labels = "%b %Y") +
  scale_y_continuous("") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLChemistry/2023/Figures/Chem_depths_2023.jpg",width=3.5, height=4)

```

```{r all data plots}

# FCR only; all sampling sites 
ggplot(subset(all_chem_long, Reservoir=='FCR'), aes(x = DateTime, y = value, col=Depth_m)) +
  geom_point(cex=2) +
  facet_grid(metric ~ Site, scales='free') +
  scale_x_datetime("Date", date_breaks="2 months", date_labels = "%d %b") +
  scale_y_continuous("Concentration") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_color_gradient("Depth (m)", high = "black", low = "deepskyblue")
ggsave("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLChemistry/2023/Figures/FCR_ChembySite_2023.jpg",width=3.5, height=4)

```

```{r save the data}
write.csv(ysi,file.path("./Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLChemistry/2023/Data/Chemistry_2013-2023.csv"), row.names=FALSE)
```
