---
title: "Flux calc collation for EDI"
author: "Abby Lewis"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

Download historical data
```{r}
# Package ID: edi.1082.1 Cataloging System:https://pasta.edirepository.org.
# Data set title: Time series of methane and carbon dioxide diffusive fluxes using an Ultraportable Greenhouse Gas Analyzer (UGGA) for Falling Creek Reservoir and Beaverdam Reservoir in southwestern Virginia, USA during 2018-2021.
# Data set creator:  Cayelan Carey - Virginia Tech 
# Data set creator:  Abigail Lewis - Virginia Tech 
# Data set creator:  Alexandria Hounshell - Virginia Tech 
# Data set creator:  Ryan McClure - Virginia Tech 
# Data set creator:  Adrienne Breef-Pilz - Virginia Tech 
# Contact:  Cayelan Carey -  Virginia Tech  - cayelan@vt.edu
# Stylesheet v2.11 for metadata conversion into program: John H. Porter, Univ. Virginia, jporter@virginia.edu 

inUrl1  <- "https://pasta.lternet.edu/package/data/eml/edi/1082/1/fbf896558989873ef6f5385ba806772b" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "Date",     
                    "Rep",     
                    "Start_time",     
                    "End_time",     
                    "Temp_C",     
                    "co2_slope_ppmS",     
                    "co2_R2",     
                    "co2_flux_umolCm2s",     
                    "ch4_slope_ppmS",     
                    "ch4_R2",     
                    "ch4_flux_umolCm2s",     
                    "Flag_co2_flux_umolCm2s",     
                    "Flag_ch4_flux_umolCm2s"    ), check.names=TRUE)
               
unlink(infile1)
		    
# Fix any interval or ratio columns mistakenly read in as nominal and nominal columns read as numeric or dates read as strings
                
if (class(dt1$Reservoir)!="factor") dt1$Reservoir<- as.factor(dt1$Reservoir)
if (class(dt1$Site)=="factor") dt1$Site <-as.numeric(levels(dt1$Site))[as.integer(dt1$Site) ]               
if (class(dt1$Site)=="character") dt1$Site <-as.numeric(dt1$Site)                                   
# attempting to convert dt1$Date dateTime string to R date structure (date or POSIXct)                                
tmpDateFormat<-"%Y-%m-%d"
tmp1Date<-as.Date(dt1$Date,format=tmpDateFormat)
# Keep the new dates only if they all converted correctly
if(length(tmp1Date) == length(tmp1Date[!is.na(tmp1Date)])){dt1$Date <- tmp1Date } else {print("Date conversion failed for dt1$Date. Please inspect the data and do the date conversion yourself.")}                                                                    
rm(tmpDateFormat,tmp1Date) 
if (class(dt1$Rep)=="factor") dt1$Rep <-as.numeric(levels(dt1$Rep))[as.integer(dt1$Rep) ]               
if (class(dt1$Rep)=="character") dt1$Rep <-as.numeric(dt1$Rep)
if (class(dt1$Temp_C)=="factor") dt1$Temp_C <-as.numeric(levels(dt1$Temp_C))[as.integer(dt1$Temp_C) ]               
if (class(dt1$Temp_C)=="character") dt1$Temp_C <-as.numeric(dt1$Temp_C)
if (class(dt1$co2_slope_ppmS)=="factor") dt1$co2_slope_ppmS <-as.numeric(levels(dt1$co2_slope_ppmS))[as.integer(dt1$co2_slope_ppmS) ]               
if (class(dt1$co2_slope_ppmS)=="character") dt1$co2_slope_ppmS <-as.numeric(dt1$co2_slope_ppmS)
if (class(dt1$co2_R2)=="factor") dt1$co2_R2 <-as.numeric(levels(dt1$co2_R2))[as.integer(dt1$co2_R2) ]               
if (class(dt1$co2_R2)=="character") dt1$co2_R2 <-as.numeric(dt1$co2_R2)
if (class(dt1$co2_flux_umolCm2s)=="factor") dt1$co2_flux_umolCm2s <-as.numeric(levels(dt1$co2_flux_umolCm2s))[as.integer(dt1$co2_flux_umolCm2s) ]               
if (class(dt1$co2_flux_umolCm2s)=="character") dt1$co2_flux_umolCm2s <-as.numeric(dt1$co2_flux_umolCm2s)
if (class(dt1$ch4_slope_ppmS)=="factor") dt1$ch4_slope_ppmS <-as.numeric(levels(dt1$ch4_slope_ppmS))[as.integer(dt1$ch4_slope_ppmS) ]               
if (class(dt1$ch4_slope_ppmS)=="character") dt1$ch4_slope_ppmS <-as.numeric(dt1$ch4_slope_ppmS)
if (class(dt1$ch4_R2)=="factor") dt1$ch4_R2 <-as.numeric(levels(dt1$ch4_R2))[as.integer(dt1$ch4_R2) ]               
if (class(dt1$ch4_R2)=="character") dt1$ch4_R2 <-as.numeric(dt1$ch4_R2)
if (class(dt1$ch4_flux_umolCm2s)=="factor") dt1$ch4_flux_umolCm2s <-as.numeric(levels(dt1$ch4_flux_umolCm2s))[as.integer(dt1$ch4_flux_umolCm2s) ]               
if (class(dt1$ch4_flux_umolCm2s)=="character") dt1$ch4_flux_umolCm2s <-as.numeric(dt1$ch4_flux_umolCm2s)
if (class(dt1$Flag_co2_flux_umolCm2s)=="factor") dt1$Flag_co2_flux_umolCm2s <-as.numeric(levels(dt1$Flag_co2_flux_umolCm2s))[as.integer(dt1$Flag_co2_flux_umolCm2s) ]               
if (class(dt1$Flag_co2_flux_umolCm2s)=="character") dt1$Flag_co2_flux_umolCm2s <-as.numeric(dt1$Flag_co2_flux_umolCm2s)
if (class(dt1$Flag_ch4_flux_umolCm2s)=="factor") dt1$Flag_ch4_flux_umolCm2s <-as.numeric(levels(dt1$Flag_ch4_flux_umolCm2s))[as.integer(dt1$Flag_ch4_flux_umolCm2s) ]               
if (class(dt1$Flag_ch4_flux_umolCm2s)=="character") dt1$Flag_ch4_flux_umolCm2s <-as.numeric(dt1$Flag_ch4_flux_umolCm2s)

ugga_2018_2021 <- dt1
```



```{r}
ugga_2022 = read_csv("../UGGA_Raw/2022/TextFiles/2022_season_Flux_Output.csv")%>%
  mutate(Date=as.Date(Date))%>%
  rename(Flag_co2_flux_umolCm2s = co2_flux_umolCm2s_flag,
         Flag_ch4_flux_umolCm2s = ch4_flux_umolCm2s_flag)

ugga_comb = ugga_2018_2021%>%
  full_join(ugga_2022)%>%
  mutate(Date = as.Date(Date))%>%
  group_by(Reservoir, Site, Date)%>%
  mutate(Rep = seq(1:n()))%>%
  select("Reservoir",
         "Site",
         "Date",
         "Rep",
         "Start_time",
         "End_time",
         "Temp_C",
         "co2_slope_ppmS",
         "co2_R2",
         "co2_flux_umolCm2s",
         "ch4_slope_ppmS",
         "ch4_R2",
         "ch4_flux_umolCm2s",
         "Flag_co2_flux_umolCm2s",
         "Flag_ch4_flux_umolCm2s")%>%
  arrange(Date)

ugga_flagged = ugga_comb%>%
  mutate(Flag_co2_flux_umolCm2s = ifelse(co2_R2<0.9,1,Flag_co2_flux_umolCm2s),
         Flag_ch4_flux_umolCm2s = ifelse(ch4_R2<0.9,1,Flag_ch4_flux_umolCm2s),
         Site = ifelse(Site==1&Reservoir=="BVR",40,Site))

write.csv(ugga_flagged, "UGGA_2018_2022.csv", row.names = F)

jpeg("UGGA_2018_2022_co2.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = co2_R2>.9)%>%
  ggplot(aes(x = Date, y = co2_slope_ppmS, color = R2))+
  geom_point()
dev.off()

jpeg("UGGA_2018_2022_ch4.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = ch4_R2>.9)%>%
  ggplot(aes(x = Date, y = ch4_slope_ppmS, color = R2))+
  geom_point()
dev.off()

min(ugga_comb$Date)
max(ugga_comb$Date)
```

```{r}
uggs = read_csv("UGGA_2018_2022.csv")

uggs = uggs%>%
  mutate(Year = year(Date))

year(uggs$Date)<-2019

uggs%>%
  filter(Reservoir=="FCR",
         Site == 50)%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date,y=ch4_flux_umolCm2s, color = Year))+
  geom_point()+
  geom_smooth()+
  ggtitle("FCR")
```



```{r}
# Install and load devtools
#install.packages("devtools")
library(devtools)

# Install and load EMLassemblyline
#install_github("EDIorg/EMLassemblyline")
library(EMLassemblyline)

# Add site descriptions

#Install the required googlesheets4 package
#install.packages('googlesheets4')
#Load the library 
library(googlesheets4)
sites <- read_sheet('https://docs.google.com/spreadsheets/d/1TlQRdjmi_lzwFfQ6Ovv1CAozmCEkHumDmbg_L4A2e-8/edit#gid=124442383')
data<- read_csv("UGGA_2018_2022.csv") #This is the line you need to modify!
trim_sites = function(data,sites){
  data_res_site=data%>% #Create a Reservoir/Site combo column
    mutate(res_site = trimws(paste0(Reservoir,Site)))
  sites_merged = sites%>% #Filter to Sites that are in the dataframe
    mutate(res_site = trimws(paste0(Reservoir,Site)))%>%
    filter(res_site%in%data_res_site$res_site)%>%
    select(-res_site)
}
sites_trimmed = trim_sites(data,sites) 
write.csv(sites_trimmed,"site_descriptions.csv", row.names=F)# Write to file


# Make the EML for EDI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_eml(path = getwd(),
         dataset.title = "Time series of methane and carbon dioxide diffusive fluxes using an Ultraportable Greenhouse Gas Analyzer (UGGA) for Falling Creek Reservoir and Beaverdam Reservoir in southwestern Virginia, USA during 2018–2022",
         data.table = c("UGGA_2018_2022.csv","site_descriptions.csv"),
         data.table.name = c("UGGA dataset 2018-2022","Sample site descriptions"),
         data.table.description = c("UGGA diffusive flux dataset from FCR and BVR","Descriptions of sampling sites, including lat/long"),
         other.entity = c('RawData.zip', "QAQC_UGGA_2018_2022.Rmd"),
         other.entity.name = c('Raw UGGA files and code', "Data compilation and publishing script"),
         other.entity.description = c('Raw data from the Ultraportable Greenhouse Gas Analyzer and code used to translate these data into the diffusive flux rates presented in this data table', "Code used to compile and QAQC all years of UGGA data, then publish to EDI"),
         temporal.coverage = c("2018-05-07", "2022-07-05"),
         maintenance.description = "ongoing",
         user.domain = "EDI",
         user.id = "ccarey",
         package.id = "edi.1002.5")
```

