---
title: "Secchi_inspection_2013_2023"
author: "Austin Delany"
date: "2023-12-08"
output: html_document
---
```{r setup packages, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Add the names of the packages 
pacman::p_load(tidyverse, lubridate)
```


```{r read in current and historic data}
current_file <- read_csv('~/Reservoirs/Data/DataNotYetUploadedToEDI/Secchi/secchi_L1.csv', col_types = cols())
#note that this file path doesn't not work for HLW - need to replace "~/Reservoirs" with "."
#and make sure wd is set to project directory

historic_file <- read_csv('https://pasta.lternet.edu/package/data/eml/edi/198/11/81f396b3e910d3359907b7264e689052', col_types = cols())

secchi <- bind_rows(current_file, historic_file)
```

```{r}
#source L1 functin to run all data through QAQC process
source("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Scripts/L1_generation_scripts/secchi_qaqc.R")

```


```{r make df longer}
#------------------------------------------------------------------------------#
#### Secchi diagnostic plots #### 
secchi_long <- secchi %>%
  mutate(year = as.factor(year(DateTime)), day = yday(DateTime))
```


```{r}
# Plot range of values per year for each reservoir; 
# annual mean value indicated with large black dot
ggplot(secchi_long, aes(x = year, y = Secchi_m, col=Reservoir)) +
  geom_point(size=1) +
  stat_summary(fun.y="mean", geom="point",pch=21,  size=3, fill='black') +
  facet_grid(. ~ Reservoir, scales= 'free_x') +
  scale_x_discrete("Date", breaks=seq(2013,2019,1)) +
  scale_y_continuous("Secchi depth (m)", breaks=seq(0,5,1), limits=c(0,5.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='none')
```

```{r}
# All reservoirs time series 
ggplot(secchi_long, aes(x = DateTime, y = Secchi_m, col=Reservoir)) +
  geom_point(size=1) +
  facet_grid(. ~ Reservoir, scales= 'free_x') +
  scale_x_datetime("Date", date_breaks= "6 months", date_labels = "%b %Y") +
  scale_y_continuous("Secchi depth (m)", breaks=seq(0,5,1), limits=c(0,5.1)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='none')
#ggsave(file.path("./Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2022/Figures/Secchi_months.jpg"),width=3.5, height=4)
```

```{r}
# Time series for each reservoir by julian day (see interannual varaibility)
#jpeg("Secchi_JulianDay.jpg", width = 6, height = 5, units = "in",res = 300)
ggplot(secchi_long, aes(x = day, y = Secchi_m)) +
  geom_point(size=2) + 
  facet_grid(Reservoir ~ ., scales= 'free_y') +
  scale_x_continuous("Julian day", limits=c(10,315), breaks=seq(50,300,50))+
  scale_y_reverse("Secchi depth (m)") +
  theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position='bottom')
ggsave(file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2022/Figures/Secchi_JulianDay.jpg"),width=3.5, height=4)
```


<!-- secchi_old <- read_csv(file.path("./Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2021/Secchi_depth_2013-2021.csv")) -->
<!-- secchi_new <- read_csv(file.path("./Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2022/Data/2022_secchi_depth_final.csv")) -->


<!-- #merge last year's EDI secchi data with new data from this year -->
<!-- secchi <- rbind(secchi_old,secchi_new) -->

<!-- # Arrange order of columns for final data table -->
<!-- secchi <- secchi %>% select(Reservoir, Site, DateTime, Secchi_m, Flag_DateTime, Flag_Secchi) %>% -->
<!--   arrange(Reservoir, DateTime)  -->

<!-- #add units to flag column for final df -->
<!-- names(secchi)[6] <- "Flag_Secchi_m"  -->

```{r}
#find duplicate rows
secchi_dup <- secchi |> 
  group_by(Reservoir, Site, DateTime) |> 
  mutate(n = n()) |> 
  filter(n > 1)

#delete duplicate rows
secchi_final <- secchi |> 
  group_by(Reservoir, Site, DateTime) |> 
  distinct(Secchi_m)

```


```{r save the data}
write.csv(secchi_final,file.path("~/Reservoirs/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLYSI_PAR_secchi/2023/Data/Secchi_depth_2013-2023.csv"), row.names=FALSE)
#replace "~/Reservoirs" with "."
```

<!-- #### secchi diagnostic plots #### -->
<!-- secchi_long <- secchi %>%  -->
<!--   gather(metric, value, Secchi_m) %>%  -->
<!--   mutate(month = strftime(DateTime, "%b")) %>% -->
<!--   mutate(DateTime = as.Date(DateTime)) -->

<!-- ggplot(secchi_long, aes(x=DateTime, y=value )) + -->
<!--   facet_wrap(~Reservoir) + geom_point(cex=2) + theme_bw() -->
