---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lubridate)
cn1 <- read.csv("MAG03Apr19.csv")
cn2 <- read.csv("MAG10Apr19.csv")
cn3 <- read.csv("MAG28mar19.csv")

cn_temp <- cn1 %>%
  full_join(cn2)%>%
  full_join(cn3)%>%
  filter(Method == "soil")%>%
  mutate(Name = tolower(Name),
         Date_run = Date,
         Res = str_extract(str_extract(Name, "(f_|fcr|b_|bvr)"),"[a-z]"),
         Depth = as.numeric(str_extract(str_extract(Name, "[0-9]+m"),"[0-9]+")),
         Rep = as.numeric(str_extract(str_extract(Name, "r[0-9]+"),"[0-9]+")),
         is.dup = str_extract(Name, "dup"),
         Date_num = as.character(as.Date(str_extract(Name, "\\d\\d\\d\\d+"), format = "%m%d%y")),
         Date_let = as.character(as.Date(str_extract(Name, "\\d+\\D\\D\\D\\d\\d"), format = "%d%b%y")),
         Date_slash = as.character(as.Date(str_extract(Name, "\\d+/\\d+/\\d+"), format = "%m/%d/%y")))%>%
  rename(Time_run = Time,
         Weight_mg = Weight...mg.,
         N_area = N..Area,
         C_Area = C..Area,
         N_pct = N.....,
         C_pct = C.....,
         CN_ratio = C.N..ratio)%>%
  select(-No.,-Hole..Pos.,-N..Factor,-C..Factor,-N..Blank,-C..Blank)
cn <- unite(cn_temp, "Date_temp", c(Date_num,Date_let,Date_slash), sep = "")%>%
  mutate(Date = as.Date(gsub("NA","",Date_temp)))%>%
  select(-Date_temp)
cn$Layer[cn$Depth %in% c(4,5)] <- "epi"
cn$Layer[cn$Depth %in% c(8,10)] <- "hypo"

cn%>%
  ggplot(aes(x = Date, y = CN_ratio, color = Res, shape = Layer))+
  geom_point()

cn_sd <- cn %>%
  group_by(Res, Layer, Date)%>%
  add_tally()%>%
  summarize(CN_ratio_mean = mean(CN_ratio, na.rm = T),
            CN_ratio_sd = sd(CN_ratio, na.rm = T),
            N_pct_mean = mean(N_pct),
            N_pct_sd = sd(N_pct),
            C_pct_mean = mean(C_pct),
            C_pct_sd = sd(C_pct),
            n = unique(n))%>%
  mutate(Year = year(Date))

cn_sd%>%
  filter(!is.na(Date))%>%
  ggplot(aes(x = Date, y = CN_ratio_mean, col = Res, lty = Layer))+
  geom_line()+
  geom_errorbar(aes(ymin = (CN_ratio_mean-CN_ratio_sd), ymax = (CN_ratio_mean+CN_ratio_sd)))+
  ylab("CN ratio")+
  xlab("")+
  facet_wrap("Year", scales = "free_x")

cn_sd%>%
  filter(!is.na(Date))%>%
  ggplot(aes(x = Date, y = C_pct_mean, col = Res, lty = Layer))+
  geom_line()+
  geom_errorbar(aes(ymin = (C_pct_mean-C_pct_sd), ymax = (C_pct_mean+C_pct_sd)))+
  ylab("C pct")+
  xlab("")+
  facet_wrap("Year", scales = "free_x")

cn_sd%>%
  filter(!is.na(Date))%>%
  ggplot(aes(x = Date, y = N_pct_mean, col = Res, lty = Layer))+
  geom_line()+
  geom_errorbar(aes(ymin = (N_pct_mean-N_pct_sd), ymax = (N_pct_mean+N_pct_sd)))+
  ylab("N pct")+
  xlab("")+
  facet_wrap("Year", scales = "free_x")

```



```{r}
library(stringr)
library(tidyverse)
library(lubridate)
sed <- read.csv("2019_SedTraps_edited.csv")
sed = sed%>%
  mutate(Day_Filtered=as.POSIXct(Day_Filtered, format = "%d-%b-%y"),
         Sed_mass_g= Filter_mass_post_filtering_g-sed$Filter_mass_pre_filtering_g,
         Sed_conc_mg_L= Sed_mass_g / Volume_filtered_mL*1000000,
         Sample_ID= tolower(Sample_ID),
         Depth = str_extract(str_extract(Sample_ID, "[0-9]+m"),"[0-9]+"),
         Rep =str_extract(str_extract(Sample_ID, "r[0-9]+"),"[0-9]+"),
         Filter =str_extract(str_extract(Sample_ID, "f[0-9]+"),"[0-9]+"),
         Type =str_extract(str_extract(Sample_ID, "f[0-9]+"),"[0-9]+"),
         Res= str_extract(Sample_ID, "(fcr|bvr|\\sb\\s|\\sf\\s)"),
         Date = str_extract(Sample_ID, "\\d+ \\D\\D\\D \\d\\d"),
         Date= as.POSIXct(Date, format = "%d %b %y"))
         
sed$Date[is.na(sed$Date)]=sed$Day_Filtered[is.na(sed$Date)]
sed$Res[is.na(sed$Res) & sed$Depth %in% c(4,8)]= "fcr"
sed$Res[is.na(sed$Res) & sed$Depth %in% c(5,10)]= "bvr"
sed$Type[is.na(sed$Type)]="sed"
sed$Type= str_extract(sed$Sample_ID, "(sed\\strap\\sleftover|st\\sleftover|ses\\snet|sed)")

write.csv(sed, "sed2.csv")

sed_traps = sed %>%
  filter(Type == "sed")%>%
  group_by(Res)%>%
  mutate(Date_out = lag(Date, order_by = Date))%>%
  group_by(Date)%>%
  mutate(Date_out = min(Date_out))%>%
  ungroup()%>%
  mutate(Days = as.numeric(difftime(Date,Date_out)),
         Dep_mg = Sed_conc_mg_L *2,
         Dep_rate_mg_day = Dep_mg/Days)
sed_traps$Layer[sed_traps$Depth %in% c(4,5)] <- "epi"
sed_traps$Layer[sed_traps$Depth %in% c(8,10)] <- "hypo"

#sed_traps$Days[is.na(sed_traps$Days),] <- 14 #This is a guess

sed_traps %>%
  ggplot(aes(x = Date, y = Dep_rate_mg_day, color = Res, shape = Layer))+
  geom_point()

sed_traps_sd <- sed_traps %>%
  group_by(Res, Layer, Date)%>%
  remove_missing(vars = "Dep_rate_mg_day")%>%
  add_tally()%>%
  summarize(dep_mean = mean(Dep_rate_mg_day, na.rm = T),
            dep_sd = sd(Dep_rate_mg_day, na.rm = T),
            n = unique(n))

sed_traps_sd%>%
  ggplot(aes(x = Date, y = dep_mean, col = Res, lty = Layer))+
  geom_line()+
  geom_errorbar(aes(ymin = (dep_mean-dep_sd), ymax = (dep_mean+dep_sd)))+
  ylab("Sediment deposition (mg/day)")+
  xlab("")+
  ggtitle("2019")

```