---
title: "Flux calc collation for EDI"
author: "Abby Lewis"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Need to fix reps for 2018
Are start and end times in real units?
How to do flags?

```{r}
ugga_2021 = read_csv("../UGGA_Raw/2021/TextFiles/20220106_Flux_Output.csv")
ugga_2020 = read_csv("../UGGA_Raw/2020/TextFiles/2020_season_Flux_Output.csv")
ugga_2019 = read_csv("../UGGA_Raw/2019/TextFiles/2019_season_Flux_Output.csv")
ugga_2018 = read_csv("../UGGA_Raw/2018/TextFiles/2018_season_Flux_Output.csv")

ugga_comb = ugga_2021%>%
  full_join(ugga_2020)%>%
  full_join(ugga_2019)%>%
  full_join(ugga_2018)%>%
  mutate(Date = as.Date(Date))%>%
  group_by(Reservoir, Site, Date)%>%
  mutate(Rep = seq(1:n()))%>%
  select("Reservoir","Site","Date","Rep","Start_time","End_time","Temp_C","co2_slope_ppmS","co2_R2",
               "co2_flux_umolCm2s","ch4_slope_ppmS","ch4_R2","ch4_flux_umolCm2s","co2_flux_umolCm2s_flag",
               "ch4_flux_umolCm2s_flag")

jpeg("UGGA_2018_2021_co2.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = co2_R2>.9)%>%
  ggplot(aes(x = Date, y = co2_slope_ppmS, color = R2))+
  geom_point()
dev.off()

jpeg("UGGA_2018_2021_ch4.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = ch4_R2>.9)%>%
  ggplot(aes(x = Date, y = ch4_slope_ppmS, color = R2))+
  geom_point()
dev.off()

min(ugga_comb$Date)
max(ugga_comb$Date)
```

