---
title: "Sed traps CN 2019-present"
author: "Abby Lewis"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

Load data for samples run in 2022/2023
```{r}
cn1 = read.csv("./2023 sed trap runs/ASL 23jan23.csv")
cn2 = read.csv("./2023 sed trap runs/ASL 24jan23.csv")
cn3 = read.csv("./2023 sed trap runs/ASL 26jan23.csv")
cn4 = read.csv("./2023 sed trap runs/ASL 27jan23.csv")
cn5 = read.csv("./2023 sed trap runs/ASL 23mar22.csv")
cn6 = read.csv("./2023 sed trap runs/ASL 10feb22.csv")
# Correct format should be F_sed_8m_R2_F2_02May22

cn_raw = cn1%>%
  full_join(cn2)%>%
  full_join(cn3)%>%
  full_join(cn4)%>%
  full_join(cn5)%>%
  full_join(cn6)%>%
  dplyr::select(-X)

cn_processed = cn_raw%>%
  filter(!Name%in%c("aa as unknown","aspartic acid","RunIn","ref zzyzx","crucible blank","internal reference zzyzx"),
         Method == "very low")%>%
  mutate(Reservoir = ifelse(substring(Name,1,1)%in%c("f","F"),"FCR",NA),
         Reservoir = ifelse(substring(Name,1,1)%in%c("b","B"),"BVR",Reservoir),
         cut = substring(Name,2),
         Date_sampled = as.Date(sub("_.*","",cut),format = "%d%b%y"),
         cut = sub("[0-9]+[a-z]+[0-9]+","",cut,ignore.case=T),
         Depth_m = as.numeric(sub("_","",sub("m.+","",cut))),
         cut = sub("_[0-9]+m_","",cut),
         cut = ifelse(cut=="r1f2","r1f2_r1f2",cut),
         Filter1ID = ifelse(grepl("_",cut), #First, standardize filter columns
                             sub("_.+","",cut),
                             paste0("r1",cut)),
         Filter2ID = ifelse(grepl("_",cut),
                             sub(".+_","",cut),
                             paste0("r2",cut)),
         Filter1ID = paste0(substr(Reservoir,1,1),"_sed_",
                             Depth_m,"m_R",substr(Filter1ID,2,2),"_F",substr(Filter1ID,4,4),"_",
                             format(Date_sampled,"%d%b%y")),
         Filter2ID = paste0(substr(Reservoir,1,1),"_sed_",
                             Depth_m,"m_R",substr(Filter2ID,2,2),"_F",substr(Filter2ID,4,4),"_",
                             format(Date_sampled,"%d%b%y")))%>%
  select(-cut,-No.,-Hole..Pos.,-Method,-Info,-C..Blank,-N..Blank)%>%
  rename(Time_run = Time,
         Weight_mg = Weight...mg.,
         N_area = N..Area,
         C_area = C..Area,
         N_pct = N.....,
         C_pct = C.....,
         CN_ratio = C.N..ratio,
         N_factor = N..Factor,
         C_factor = C..Factor,
         Date_run = Date)

cn_processed%>%
  mutate(layer=ifelse(Depth_m%in%c(4,5),"EPI","HYPO"))%>%
  ggplot(aes(x=Date_sampled,y=C_pct,color=layer))+
  #ggplot(aes(x=Date_sampled,y=C_pct,color=as.factor(Depth_m)))+
  geom_point()+
  facet_wrap(~Reservoir)

cn_to_combine = cn_processed%>%
  dplyr::select(Weight_mg,
                N_pct,
                C_pct,
                Filter1ID,
                Filter2ID,
                Date_sampled)
```

This bit is copied from the metals script and could be standardized in the future
```{r}
frame1 = read.csv("../Filtering logs/FilteringLog_EDI.csv")

#let's use the first filter ID to extract reservoir and depth info (should be the same year to year)
#also add in info that never changes
frame2 = cn_to_combine
frame2 <- frame2 %>% 
  mutate(Reservoir = ifelse(substring(frame2$Filter1ID, 1,1) == 'F','FCR',NA),
         Reservoir = ifelse(substring(frame2$Filter1ID, 1,1) == 'B','BVR', Reservoir),
         Depth_m = as.numeric(str_extract(frame2$Filter1ID, '(?<=_)[:digit:]+(?=m)')),
         Site = 50)
#

#Set up empty columns
frame2_complete = frame2%>%
  mutate(CombinedCollectionVol_L = NA,
         CombinedFilterVol_L = NA,
         CombinedSedMass_g = NA,
         CombinedXSA_m2 = NA,
         Duration_days = NA,
         Volume_flag = NA)
#Loop through all rows and sum data
for(i in 1:nrow(frame2_complete)){
  filter1 = frame1%>%filter(tolower(FilterID)==tolower(frame2_complete$Filter1ID[i])) #filter to the first filter
  filter2 = frame1%>%filter(tolower(FilterID)==tolower(frame2_complete$Filter2ID[i])) #filter to the second filter
  if(nrow(filter1)==1&nrow(filter2)==1){
    frame2_complete$CombinedCollectionVol_L[i]=filter1$CollectionVol_L+filter2$CollectionVol_L #sum collection volumes
    frame2_complete$CombinedFilterVol_L[i]=filter1$FilterVol_L+filter2$FilterVol_L #sum filter volumes
    frame2_complete$CombinedSedMass_g[i]=filter1$SedMass_g+filter2$SedMass_g #sum sed mass
    frame2_complete$CombinedXSA_m2[i]=filter1$TrapXSA_m2+filter2$TrapXSA_m2 #sum surface area
    frame2_complete$Duration_days[i]=filter1$Duration_days #save duration
    frame2_complete$Volume_flag[i]=ifelse(filter1$Flag_CollectionVol_L==2|filter2$Flag_CollectionVol_L==2,2,1) #Save flag for volume
  } else { 
    if(!nrow(filter1)==1){warning(
      paste0("Filter ",
             frame2_complete$Filter1ID[i], 
             " is in the filtering log ",  nrow(filter1)," times\n"))}
    if(!nrow(filter2)==1){warning(
      paste0("Filter ",
             frame2_complete$Filter2ID[i], 
             " is in the filtering log ",  nrow(filter2)," times\n"))}
  }
}
```

Now that we have sed weights, finish processing
```{r}
CN_DONE = frame2_complete%>%
  filter(!is.na(CombinedXSA_m2))%>%
  rename(Entered_weight_mg = Weight_mg)%>%
  mutate(C_mass_CN_g = C_pct/100*Entered_weight_mg/1000,#convert to g
         N_mass_CN_g = N_pct/100*Entered_weight_mg/1000,
         C_pct = C_mass_CN_g/CombinedSedMass_g*100, #convert to pct
         N_pct = N_mass_CN_g/CombinedSedMass_g*100)%>%
  dplyr::select(Reservoir,Date_sampled,Depth_m,Site,Duration_days,Filter1ID,Filter2ID,CombinedCollectionVol_L,CombinedFilterVol_L,CombinedSedMass_g,CombinedXSA_m2,C_mass_CN_g,N_mass_CN_g)%>%
  mutate(Filt_ratio = CombinedCollectionVol_L/CombinedFilterVol_L,
         C_mass_traps_g = C_mass_CN_g*Filt_ratio,
         N_mass_traps_g = N_mass_CN_g*Filt_ratio,
         C_flux_gm2d = C_mass_traps_g/CombinedXSA_m2/Duration_days,
         N_flux_gm2d = N_mass_traps_g/CombinedXSA_m2/Duration_days)
  

CN_DONE%>%
  ggplot(aes(x = Date_sampled,y=C_flux_gm2d,color = as.factor(Depth_m)))+
  geom_point()+
  facet_wrap(~Reservoir)

metals_to_combine = read.csv("../Metals/2022_FeMnCN.csv")%>%
  mutate(Date=as.Date(Date))

comb_raw = CN_DONE%>%
  rename(Date = Date_sampled)%>%
  full_join(metals_to_combine)

comb_formatted = comb_raw%>%
  rename(TOCFlux_gm2d=C_flux_gm2d,
         TNFlux_gm2d = N_flux_gm2d,
         TOC_g = C_mass_traps_g,
         TN_g = N_mass_traps_g)%>%
  dplyr::select(Reservoir, 
                Date,
                Site,
                Duration_days,
                Depth_m,
                CombinedXSA_m2,
                Filter1ID,
                Filter2ID,
                CombinedCollectionVol_L,
                CombinedFilterVol_L,
                CombinedSedMass_g,
                ICPTFe_mgL,
                ICPTMn_mgL,
                AcidVol_L,
                DilutionFactor,
                TFe_g,
                TMn_g,
                TFeFlux_gm2d,
                TMnFlux_gm2d,
                TOC_g,
                TN_g,
                TOCFlux_gm2d,
                TNFlux_gm2d)%>%
  arrange(Date)

write.csv(comb_formatted,"../CN_Metals_Flux_EDI.csv",row.names=F)

mean(unique(frame1$CollectionVol_L), na.rm=T)
```
