---
title: "MakeEMLCTD"
author: "Abby Lewis"
date: "12/16/2019"
output: html_document
---

Load packages 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

# Install and load devtools (used for install_github() function below)
#install.packages("devtools")
#library(devtools)

# Install and load EMLassemblyline
#install_github("EDIorg/EMLassemblyline")
library(EMLassemblyline)

#Install the required googlesheets4 package
#install.packages('googlesheets4')
#Load the library 
library(googlesheets4)
```

Run some manual QAQC (consider adding this to automation in the future)
NOTE: We decided at the last minute in 2024 to systematically remove excessively high turbidity and PAR. I am leaving this here because you may want to change these thresholds or change how this is implemented in the future

```{r}
ctd <- read.csv("../CTD_2013_2023.csv")
ctd_fix <- ctd %>%
  mutate(
    #remove and flag excessively high turbidity
    Flag_Turbidity_NTU = ifelse(!is.na(Turbidity_NTU) & Turbidity_NTU > 200, 2, Flag_Turbidity_NTU),
    Turbidity_NTU = ifelse(!is.na(Turbidity_NTU) & Turbidity_NTU > 200, NA, Turbidity_NTU),
    
    #remove and flag excessively high PAR
    Flag_PAR_umolm2s = ifelse(!is.na(PAR_umolm2s) & PAR_umolm2s > 3000, 2, Flag_PAR_umolm2s),
    PAR_umolm2s = ifelse(!is.na(PAR_umolm2s) & PAR_umolm2s > 3000, NA, PAR_umolm2s)
         )

write.csv(ctd_fix, "CTD_2013_2023.csv", row.names = FALSE)
```

Refresh site list

```{r}
sites <- read_sheet('https://docs.google.com/spreadsheets/d/1TlQRdjmi_lzwFfQ6Ovv1CAozmCEkHumDmbg_L4A2e-8/edit#gid=124442383')

trim_sites = function(data,sites){
  data_res_site=data %>% #Create a Reservoir/Site combo column
    mutate(res_site = trimws(paste0(Reservoir,Site)))
  sites_merged = sites %>% #Filter to Sites that are in the dataframe
    mutate(res_site = trimws(paste0(Reservoir,Site))) %>%
    filter(res_site %in% data_res_site$res_site) %>%
    select(-res_site)
}

sites_trimmed = trim_sites(ctd_fix, sites) 
write.csv(sites_trimmed,"site_descriptions.csv", row.names=F) #Write to file
```

Make EML

```{r}
# Make the EML for EDI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_eml(path = getwd(),
         dataset.title = "Time series of high-frequency profiles of depth, temperature, dissolved oxygen, conductivity, specific conductance, chlorophyll a, turbidity, pH, oxidation-reduction potential, photosynthetically active radiation, colored dissolved organic matter, phycocyanin, phycoerythrin, and descent rate for Beaverdam Reservoir, Carvins Cove Reservoir, Falling Creek Reservoir, Gatewood Reservoir, and Spring Hollow Reservoir in southwestern Virginia, USA 2013-2023",
         data.table = c("CTD_2013_2023.csv",
                        "site_descriptions.csv", 
                        "CTD_Maintenance_Log.csv"),
         data.table.name = c("CTD dataset 2013-2023",
                             "Descriptions of sample sites",
                             "Maintenance log 2013 - 2023"),
         data.table.description = c("Reservoir CTD dataset",
                                    "Sample site descriptions",
                                    "Log of data issues that have been flagged or addressed in the final data publication"),
         other.entity = c('CTD_QAQC_2013_2023.R', 
                          'CTD_Visualization_2023.qmd',
                          "helper_scripts.zip"),
         other.entity.name = c('QAQC script', 
                               "Visualization script",
                               "Helper scripts"),
         other.entity.description = c('High-level QAQC script used to process data from 2018-2023: references scripts in helper_scripts.zip', 
                                      'Script that plots the data for visual inspection during the publishing process',
                                      "Scripts used to compile casts and apply QAQC, 
                                      as referenced by CTD_QAQC_2018_2023.R"),
         temporal.coverage = c("2013-03-07", "2023-12-04"),
         maintenance.description = "ongoing",
         user.domain = "EDI",
         user.id = "ccarey",
         package.id = "edi.200.14") #2024
```

