---
title: "Catwalk for EDI"
author: "Abby Lewis"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load("RCurl","tidyverse","lubridate")
source("temp_oxy_chla_qaqc.R")
```

TO DO 
- compare with CTD and add in flags/remove data as needed
- Get the correct date for the end of published data
- Add 1m QAQC?

Section 1: Load data
```{r}
#Load maintenance log
download.file("https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/fcre-catwalk-data/CAT_MaintenanceLog.txt","CAT_MaintenanceLog_2020.txt")

#Load catwalk data
download.file("https://raw.githubusercontent.com/FLARE-forecast/FCRE-data/fcre-catwalk-data/Catwalk.csv","Catwalk_2020.csv")

#QAQC catwalk data
temp_oxy_chla_qaqc('Catwalk_2020.csv',"CAT_MaintenanceLog_2020.txt","Catwalk_final_2020.csv") 

#Load QAQCed catwalk data
catdata <- read.csv("Catwalk_final_2020.csv")
catdata$DateTime<-as.POSIXct(catdata$DateTime,format = "%Y-%m-%d %H:%M:%S") #Format dates as dates

catdata_published <- catdata[catdata$DateTime<="2019-12-16",] #Separate data that has already been published
catdata_published <- catdata_published[!is.na(catdata_published$Flag_All),]
catdata_flag <- catdata[catdata$DateTime>"2019-12-16",] #Work with unpublished data

#Create flagging variables
catdata_flag$Flag_All <- 0
catdata_flag$Flag_DO_1 <- 0
catdata_flag$Flag_DO_5 <- 0
catdata_flag$Flag_DO_9 <- 0
catdata_flag$Flag_Chla <- 0
catdata_flag$Flag_Phyco <- 0
catdata_flag$Flag_TDS <- 0

# Flag values
# 0: no flag
# 1: value removed due to maintenance and set to NA
# 3: negative values set to 0
# 5: questionable value due to potential fouling
# 6: very questionable value due to potential fouling. Values adjusted using a linear or square root function to match high-resolution CTD profiles are given in RDO_mgL_5 and RDO_sat_percent_5
# 7: missing data

```

Section 2: Basic QAQC/flags
```{r}
# now fix the negative DO values
catdata_flag <- catdata_flag %>%  #RDO at 5m
  mutate(Flag_DO_5 = ifelse(RDO_mgL_5 < 0 | RDOsat_percent_5 < 0, 3, Flag_DO_5), #Add a flag for DO<0
         RDO_mgL_5 = ifelse(RDO_mgL_5 < 0, 0, RDO_mgL_5), #Change negative to 0
         RDOsat_percent_5 = ifelse(RDOsat_percent_5 < 0, 0, RDOsat_percent_5), #Change negative %sat to 0
         Flag_DO_5 = ifelse(is.na(RDO_mgL_5),7,Flag_DO_5), #Flag NA values
         
         Flag_DO_9 = ifelse(RDO_mgL_9 < 0 | RDOsat_percent_9 < 0, 3, Flag_DO_9), #repeat for 9m
         RDO_mgL_9 = ifelse(RDO_mgL_9 < 0, 0, RDO_mgL_9),
         RDOsat_percent_9 = ifelse(RDOsat_percent_9 < 0, 0, RDOsat_percent_9),
         Flag_DO_9 = ifelse(is.na(RDO_mgL_9),7,Flag_DO_9),
         
         Flag_DO_1 = ifelse(EXODO_mgL_1 < 0 | EXODOsat_percent_1 <0, 3, Flag_DO_1), #and for 1m
         EXODO_mgL_1 = ifelse(EXODO_mgL_1 < 0, 0, EXODO_mgL_1),
         EXODOsat_percent_1 = ifelse(EXODOsat_percent_1 <0, 0, EXODOsat_percent_1),
         Flag_DO_1 = ifelse(is.na(EXODO_mgL_1),7,Flag_DO_1))
```

Section 3: remove maintenance data
```{r}
#Deal with when the sensors were up
maint = read.csv("CAT_MaintenanceLog_2020.txt")
maint = maint[!grepl("EXO",maint$parameter),] #creating file "maint" with all sensor string maintenance
clean_start<-as.POSIXct(maint$TIMESTAMP_start)
clean_end <- as.POSIXct(maint$TIMESTAMP_end)

ADJ_PERIOD = 2*60*60 #amount of time to stabilization after cleaning in seconds

for (i in range(1,length(clean_start))){ #Set all data during cleaning and for ADJ_PERIOD after to NA
  catdata_flag$RDO_mgL_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<(clean_end[i]+ADJ_PERIOD)] <- NA
  catdata_flag$RDO_mgL_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$RDOsat_percent_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$RDOsat_percent_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$Flag_DO_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- 1
  catdata_flag$Flag_DO_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- 1
}
```



Section 4: Deal with fouling
Dexter this is the section I would love help with!!



```{r}
################
#Creating a new flag "6" started in 2019: "very questionable value due to potential fouling. Values adjusted using a linear or square root function to match high-resolution CTD profiles are given in RDO_mgL_5 and RDO_sat_percent_5"
#Creating a new flag "5" which means that the values are very questionable due to fouling but not adjusted (starting in 2019)
################

catdata_adj = catdata_flag%>%
  mutate(
     # 5 meters
    #Add a flag that this period was suspect
     Flag_DO_5 = ifelse(DateTime<as_datetime("2019-08-12 12:40:00") & DateTime> as_datetime("2019-08-11 00:00:00"), 6, Flag_DO_5), 
     #Adjust DO (mg/L) creating a new variable
     RDO_mgL_5_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-11 00:00:00", 
                                RDO_mgL_5 + sqrt(as.numeric(difftime(DateTime,"2019-08-11 00:00:00", units = "mins")))/30,
                                RDO_mgL_5), #If the date is within this interval, the adjusted values is the measured value plus the squareroot of the number of minutes since the start of the interval divided by 30 -- determined through trial and error
     #Adjust %sat
     RDOsat_percent_5_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-11 00:00:00", 
                                RDOsat_percent_5 + sqrt(as.numeric(difftime(DateTime,"2019-08-11 00:00:00", units = "mins")))/30/11.3*100, #Same as DO_mgL except converted to pSat by multiplying by 100/11.3
                                RDOsat_percent_5),
     Flag_DO_5 = ifelse(DateTime<as_datetime("2019-07-17 11:40:00") & DateTime> as_datetime("2019-07-13 00:00:00"), 5, Flag_DO_5),
     
     #9 meters 
     Flag_DO_9 = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00",6, Flag_DO_9),
     RDO_mgL_9_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00", 
                                RDO_mgL_9 + sqrt(as.numeric(difftime(DateTime,"2019-08-05 12:45:00", units = "mins")))/70, #A different square root adjustment here
                                RDO_mgL_9),
     RDOsat_percent_9_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00", 
                                RDOsat_percent_9 + sqrt(as.numeric(difftime(DateTime,"2019-08-05 12:45:00", units = "mins")))/70/11.3*100,
                                RDOsat_percent_9),
     Flag_DO_9 = ifelse(DateTime<as_datetime("2019-07-17 11:40:00") & DateTime> as_datetime("2019-07-13 00:00:00"), 5, Flag_DO_9),
     Flag_DO_9 = ifelse(DateTime<as_datetime("2019-08-19 13:00:00") & DateTime> as_datetime("2019-08-12 12:40:00"), 5, Flag_DO_9),
     
     # 9 meters september
     Flag_DO_9 = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00",6, Flag_DO_9),
     RDO_mgL_9_adjusted = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00", 
                                RDO_mgL_9 + as.numeric(difftime(DateTime,"2019-09-02 13:00:00", units = "mins"))/30000, #A linear adjustment here
                                RDO_mgL_9_adjusted),
     RDOsat_percent_9_adjusted = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00", 
                                RDOsat_percent_9 + as.numeric(difftime(DateTime,"2019-09-02 13:00:00", units = "mins"))/30000/11.3*100,
                                RDOsat_percent_9_adjusted))
```

Section 5 plot catwalk and ctd
```{r}
library(plotly)
ctd = read_csv("ctd_2018-2020_flagged.csv")%>%
  filter(Date>"2020-01-01")%>%
  filter(Reservoir == "FCR", Site == 50)

depths <- c(1.6,5,9)
newDepths <- depths
df.final<-ctd %>% group_by(Date) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final <- rbind(df.final,ctd_atThisDepth)
}
# Re-arrange the data frame by date
ctd_new <- arrange(df.final, Date)
# Round each extracted depth to the nearest 10th. 
ctd_new$Depth_m <- round(as.numeric(ctd_new$Depth_m), digits = 0.5)
ctd_new$Date <- ymd_hms(ctd_new$Date)
  

plot = catdata_adj%>%
  ggplot(aes(x = DateTime))+
  geom_line(aes(y = RDO_mgL_5), color = "blue")+
  geom_line(aes(y = RDO_mgL_9), color = "red")+
  geom_point(aes(x = Date, y = DO_mgL), data = ctd_new%>% filter(Depth_m == 5), color = "blue")+
  geom_point(aes(x = Date, y = DO_mgL), data = ctd_new%>% filter(Depth_m == 9), color = "red")
ggplotly(plot)
```

Section 6: Write final CSV
```{r}
catdata_final <- catdata_published%>%
  full_join(catdata_adj)%>%
  select(Reservoir, Site, DateTime, ThermistorTemp_C_surface, ThermistorTemp_C_1, ThermistorTemp_C_2, ThermistorTemp_C_3, ThermistorTemp_C_4, ThermistorTemp_C_5, ThermistorTemp_C_6, ThermistorTemp_C_7, ThermistorTemp_C_8, ThermistorTemp_C_9, RDO_mgL_5, RDOsat_percent_5, RDOTemp_C_5, RDO_mgL_9, RDOsat_percent_9, RDOTemp_C_9, EXOTemp_C_1, EXOCond_uScm_1, EXOSpCond_uScm_1, EXOTDS_mgL_1, EXODOsat_percent_1, EXODO_mgL_1, EXOChla_RFU_1, EXOChla_ugL_1, EXOBGAPC_RFU_1, EXOBGAPC_ugL_1, EXOfDOM_RFU_1, EXOfDOM_QSU_1, EXO_pressure, EXO_depth, EXO_battery, EXO_cablepower, EXO_wiper, RECORD, CR6_Batt_V, CR6Panel_Temp_C, RDO_mgL_5_adjusted, RDOsat_percent_5_adjusted, RDO_mgL_9_adjusted, RDOsat_percent_9_adjusted, Flag_All, Flag_DO_1, Flag_DO_5, Flag_DO_9, Flag_Chla, Flag_Phyco, Flag_TDS)

catdata_final <- catdata_final[!is.na(catdata_final$Reservoir),]
catdata_final <- catdata_final[year(catdata_final$DateTime)<2021,]

write_csv(catdata_final,"catdata_edited_withDO.csv")
```
