---
title: "Flux calc collation for EDI"
author: "Abby Lewis"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
ugga_2021 = read_csv("../UGGA_Raw/2021/TextFiles/20220106_Flux_Output.csv")
ugga_2020 = read_csv("../UGGA_Raw/2020/TextFiles/2020_season_Flux_Output.csv")
ugga_2019 = read_csv("../UGGA_Raw/2019/TextFiles/2019_season_Flux_Output.csv")
ugga_2018 = read_csv("../UGGA_Raw/2018/TextFiles/2018_season_Flux_Output.csv")

ugga_comb = ugga_2021%>%
  full_join(ugga_2020)%>%
  full_join(ugga_2019)%>%
  full_join(ugga_2018)%>%
  mutate(Date = as.Date(Date))%>%
  group_by(Reservoir, Site, Date)%>%
  mutate(Rep = seq(1:n()))%>%
  rename(Flag_co2_flux_umolCm2s = co2_flux_umolCm2s_flag,
         Flag_ch4_flux_umolCm2s = ch4_flux_umolCm2s_flag)%>%
  select("Reservoir",
         "Site",
         "Date",
         "Rep",
         "Start_time",
         "End_time",
         "Temp_C",
         "co2_slope_ppmS",
         "co2_R2",
         "co2_flux_umolCm2s",
         "ch4_slope_ppmS",
         "ch4_R2",
         "ch4_flux_umolCm2s",
         "Flag_co2_flux_umolCm2s",
         "Flag_ch4_flux_umolCm2s")%>%
  arrange(Date)

ugga_flagged = ugga_comb%>%
  mutate(Flag_co2_flux_umolCm2s = ifelse(co2_R2<0.9,1,Flag_co2_flux_umolCm2s),
         Flag_ch4_flux_umolCm2s = ifelse(ch4_R2<0.9,1,Flag_ch4_flux_umolCm2s))

summary(ugga_flagged)

write.csv(ugga_flagged, "UGGA_2018_2021.csv", row.names = F)

jpeg("UGGA_2018_2021_co2.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = co2_R2>.9)%>%
  ggplot(aes(x = Date, y = co2_slope_ppmS, color = R2))+
  geom_point()
dev.off()

jpeg("UGGA_2018_2021_ch4.jpeg", res = 300, width = 6, height = 4, units = "in")
ugga_comb%>%
  mutate(R2 = ch4_R2>.9)%>%
  ggplot(aes(x = Date, y = ch4_slope_ppmS, color = R2))+
  geom_point()
dev.off()

min(ugga_comb$Date)
max(ugga_comb$Date)
```

```{r}
uggs = read_csv("UGGA_2018_2021.csv")

uggs = uggs%>%
  mutate(Year = year(Date))

year(uggs$Date)<-2019

uggs%>%
  filter(Reservoir=="FCR",
         Site == 50)%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date,y=ch4_flux_umolCm2s, color = Year))+
  geom_point()+
  geom_smooth()+
  ggtitle("FCR")
```



```{r}
# Install and load devtools
install.packages("devtools")
library(devtools)

# Install and load EMLassemblyline
install_github("EDIorg/EMLassemblyline")
library(EMLassemblyline)

# Make the EML for EDI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_eml(path = getwd(),
         dataset.title = "Time series of methane and carbon dioxide diffusive fluxes using an Ultraportable Greenhouse Gas Analyzer (UGGA) for Falling Creek Reservoir and Beaverdam Reservoir in southwestern Virginia, USA during 2018–2021",
         data.table = "UGGA_2018_2021.csv",
         data.table.name = "UGGA dataset 2018-2021",
         data.table.description = c("UGGA diffusive flux dataset from FCR and BVR"),
         other.entity = c('RawData.zip', "QAQC_UGGA_2018_2021.Rmd"),
         other.entity.name = c('Raw UGGA files and code', "Data compilation and publishing script"),
         other.entity.description = c('Raw data from the Ultraportable Greenhouse Gas Analyzer and code used to translate these data into the diffusive flux rates presented in this data table', "Code used to compile and QAQC all years of UGGA data, then publish to EDI"),
         temporal.coverage = c("2018-05-07", "2021-04-26"),
         maintenance.description = "ongoing",
         user.domain = "EDI",
         user.id = "ccarey",
         package.id = "edi.1082.1")
```

