name: Metals QAQC
on:
  workflow_dispatch:
  schedule:
  - cron: "10 10 * * *"
  
jobs:
  metals:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/tidyverse:4.2
    steps:
      - run: git config --system --add safe.directory '*'
      
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run automated target files
        run: |
          R -e 'remotes::install_version("gsheet", version = "0.4.5")'
          R -e 'remotes::install_version("EDIutils", version = "1.0.2")'
          R -e 'remotes::install_version("xml2", version = "1.3.3")'
          R -e 'remotes::install_version("pacman", version = "0.5.1")'
          #R -e 'remotes::install_version("rqdatatable", version= "1.3.3")'
          R -e 'utils::install.packages("rqdatatable")'
          R -e 'remotes::install_version("hms", version="1.1.3")'
          R -e 'utils::install.packages("RCurl")'
          Rscript $GITHUB_WORKSPACE/Scripts/L1_generation_scripts/metals_qaqc.R

      
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add -f Data/DataNotYetUploadedToEDI/Metals_Data/metals_L1.csv
          git add Data/DataNotYetUploadedToEDI/FCR_ISCO/ISCO_metals_L1.csv
          git commit -m "Updating Manual Files" || echo "No changes to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY} 

   # Add in Healthcheck after talking to Austin       
     # - name: Healthcheck
      #  run: |
       #   sudo apt-get update
       #   sudo apt-get install -y curl
       #  curl -m 10 --retry 5 https://hc-ping.com/6175c372-eb30-4450-a985-65bd7b82dbb3
