name: Secchi QAQC
on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * *"
  
jobs:
  secchi:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/tidyverse:4.2
    steps:
      - run: git config --system --add safe.directory '*'
      
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run automated target files
        run: |
          R -e 'remotes::install_version("gsheet", version = "0.4.5")'
          R -e 'remotes::install_version("EDIutils", version = "1.0.2")'
          R -e 'remotes::install_version("xml2", version = "1.3.3")'
          R -e 'remotes::install_version("pacman", version = "0.5.1")'
          R -e 'utils::install.packages("RCurl")'
          Rscript $GITHUB_WORKSPACE/Scripts/L1_generation_scripts/secchi_qaqc.R

      
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add Data/DataNotYetUploadedToEDI/Secchi/secchi_L1.csv
          git commit -m "Updating Manual Files" || echo "No changes to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY} 
          
      - name: Healthcheck
        run: |
          curl -m 10 --retry 5 https://hc-ping.com/0d45fa1c-5110-4aa6-ac67-a53174541516