name: UGGA QAQC
on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"
  
jobs:
  ghg:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/tidyverse:4.2
    steps:
      - run: git config --system --add safe.directory '*'

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run automated target files
        run: |
          R -e 'remotes::install_version("pacman", version = "0.5.1")'
          R -e 'utils::install.packages("RCurl")'
          Rscript $GITHUB_WORKSPACE/Scripts/L1_generation_scripts/UGGA_qaqc.R
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add Data/DataNotYetUploadedToEDI/UGGA/UGGA_L1.csv
          git commit -m "Updating Manual Files" || echo "No changes to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}
          
    #  - name: Healthchecks
    #    run: |
    #      sudo apt-get update
    #      sudo apt-get install -y curl
    #      curl -m 10 --retry 5 https://hc-ping.com/46cfa878-1fd4-4ebb-abcc-87f84071c9ab
